/*
Copyright 2022-2024 NXP

NXP Confidential. This software is owned or controlled by NXP and may only
be used strictly in accordance with the applicable license terms. By expressly accepting
such terms or by downloading, installing, activating and/or otherwise using
the software, you are agreeing that you have read, and that you agree to
comply with and are bound by, such license terms. If you do not agree to
be bound by the applicable license terms, then you may not retain,
install, activate or otherwise use the software.
*/

#include <stdio.h>
#include <stdint.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <errno.h>
#include <fcntl.h>
#include <unistd.h>
#include <sys/mman.h>
#include <string.h>
#include <stdlib.h>
#include "host_vspa_if.h"

#define MBOX_SEND			0
#define MBOX_RECV			1

#define MAX_NUM_MSG		8
uint64_t modem_ccsr_base_phy=0, vspa_dmem_base_phy=0, ddr_host_vspa_view_offset=0;
uint32_t num_msg=1, core_id[MAX_NUM_MSG], mbox_id[MAX_NUM_MSG], msb32[MAX_NUM_MSG], lsb32[MAX_NUM_MSG], ccsr_src=0, test_tool_la9310=0;

static inline void get_modem_ccsr_base_phy(uint64_t* pvalues)
{
    char cfg[256], *stopstring;
    FILE *fp;

    if((fp = fopen("/usr/local/etc/fr1_fr2_test_tool_modem_bar0.cfg", "r")) == NULL) 
	{
        return;
    } 
	else 
	{
        if (fgets(cfg, 256, fp) != NULL) 
		{
            *pvalues++ = strtoull(cfg, &stopstring, 0);
        }
         if (fgets(cfg, 256, fp) != NULL) 
		{
            *pvalues++ = strtoull(cfg, &stopstring, 0);
        }
        if (fgets(cfg, 256, fp) != NULL) 
		{
            *pvalues++ = strtoull(cfg, &stopstring, 0);
        }
   }
}

static void usage(char *argv[])
{
	printf("VSPA mailbox tool v4.0 for fr1 fr2 test tool.\n");
    printf("%s send   core_id mbox_id msb32 lsb32                                                     : send 1 msg\n", argv[0]);
    printf("%s recv   core_id mbox_id                                                                 : recv 1 msg\n", argv[0]);
    printf("%s ifsend modem_ccsr_base_phy vspa_dmem_base_phy DDR_host_vspa_view_offset core_id mbox_id msb32 lsb32 [core_id mbox_id msb32 lsb32] ...   : send up to 8 msg.\n", argv[0]);
    printf("%s ifrecv modem_ccsr_base_phy vspa_dmem_base_phy DDR_host_vspa_view_offset core_id mbox_id [core_id mbox_id] ...   : recv up to 8 msg.\n", argv[0]);
	printf("   send and recv requires modem bar0 address provided in /usr/local/etc/fr1_fr2_test_tool_modem_bar0.cfg which is generated by FR1 FR2 Test Tool channels_start.sh, in case it's not there, users can generate it by: \n");
	printf("      echo 0xABCDEFGHIJ > /usr/local/etc/fr1_fr2_test_tool_modem_bar0.cfg   #0xABCDEFGHIJ is modem_ccsr_base_phy of LA device, such as 0xa048000000\n");
	printf("   ifsend, ifrecv is suggested as it will not have file access for modem addresses.\n");
}

int main (int argc, char *argv[])
{
    if(argc < 4) {
        printf("Wrong number of parameters\n");
        usage(argv);
        return -1;
    }
    

	uint32_t argvidx=2, send_recv;
	errno = 0;
	if (strcmp(argv[1], "send") == 0)
	{
		send_recv = MBOX_SEND;
		if( ((argc-2)%4) != 0) {
			printf("Wrong number of parameters\n");
			usage(argv);
			return -1;
		}
	}
	else if (strcmp(argv[1], "ifsend") == 0)
	{
		send_recv = MBOX_SEND;
		if( ((argc-5)%4) != 0) {
			printf("Wrong number of parameters\n");
			usage(argv);
			return -1;
		}
		num_msg = (argc-5)/4;
		if(num_msg>MAX_NUM_MSG)
		{
			printf("Too many mbox messages. MAX 8.\n");
			return -1;
		}
		modem_ccsr_base_phy = strtoull(argv[argvidx], NULL, 0);
		if (errno) {
			perror("Error converting physical address modem_ccsr_base_phy ");
			return -1;
		}
		argvidx++;
		vspa_dmem_base_phy = strtoull(argv[argvidx], NULL, 0);
		if (errno) {
			perror("Error converting vspa_dmem_base_phy");
			return -1;
		}
		argvidx++;
		ddr_host_vspa_view_offset = strtoull(argv[argvidx], NULL, 0);
		if (errno) {
			perror("Error converting ddr_host_vspa_view_offset");
			return -1;
		}
		argvidx++;
	}
	else if (strcmp(argv[1], "ifrecv") == 0)
	{
		send_recv = MBOX_RECV;
		if( ((argc-5)%2) != 0) {
			printf("Wrong number of parameters\n");
			usage(argv);
			return -1;
		}
		num_msg = (argc-5)/2;
		if(num_msg>MAX_NUM_MSG)
		{
			printf("Too many mbox messages. MAX 8.\n");
			return -1;
		}
		modem_ccsr_base_phy = strtoull(argv[argvidx], NULL, 0);
		if (errno) {
			perror("Error converting physical address modem_ccsr_base_phy ");
			return -1;
		}
		argvidx++;
		vspa_dmem_base_phy = strtoull(argv[argvidx], NULL, 0);
		if (errno) {
			perror("Error converting vspa_dmem_base_phy");
			return -1;
		}
		argvidx++;
		ddr_host_vspa_view_offset = strtoull(argv[argvidx], NULL, 0);
		if (errno) {
			perror("Error converting ddr_host_vspa_view_offset");
			return -1;
		}
		argvidx++;
	}
	else if (strcmp(argv[1], "recv") == 0)
	{
		send_recv = MBOX_RECV;
		if( ((argc-2)%2) != 0) {
			printf("Wrong number of parameters\n");
			usage(argv);
			return -1;
		}
	}
	else
	{
       printf("command must be 'send' 'recv' 'ifsend' 'ifrecv'\n");
       usage(argv);
       return -1;
	}
	
	if(modem_ccsr_base_phy == 0)
	{
		uint64_t values[3];
		values[0]=0; values[1]=0; values[2]=0; 
		get_modem_ccsr_base_phy(values);
		modem_ccsr_base_phy = values[0];
		vspa_dmem_base_phy = values[1];
		ddr_host_vspa_view_offset = values[2];
		if (modem_ccsr_base_phy == 0)
			return -1;	
	}
	
	int num_cores = hvif_init(modem_ccsr_base_phy, vspa_dmem_base_phy, ddr_host_vspa_view_offset, 0);

	if(send_recv == MBOX_SEND)
	{
		for(int i=0;i<num_msg;i++)
		{
			core_id[i] = strtoul(argv[argvidx], NULL, 10);
			if (core_id[i] >= num_cores) {
				printf("Invalid vspa core id %d, should be smaller than %d\n", core_id[i], num_cores);
				return -1;
			}
			argvidx++;
			
			mbox_id[i] = strtoul(argv[argvidx], NULL, 10);
			if (mbox_id[i] > 1) {
				printf("Invalid mail box id, should be either 0 or 1.\n");
				return -1;
			}
			argvidx++;

			msb32[i] = strtoul(argv[argvidx], NULL, 0);
			argvidx++;

			lsb32[i] = strtoul(argv[argvidx], NULL, 0);
			argvidx++;
		}
	}
	else
	{
		for(int i=0;i<num_msg;i++)
		{
			core_id[i] = strtoul(argv[argvidx], NULL, 10);
			if (core_id[i] >= num_cores) {
				printf("Invalid vspa core id %d, should be smaller than %d\n", core_id[i], num_cores);
				return -1;
			}
			argvidx++;
			
			mbox_id[i] = strtoul(argv[argvidx], NULL, 10);
			if (mbox_id[i] > 1) {
				printf("Invalid mail box id, should be either 0 or 1.\n");
				return -1;
			}
			argvidx++;
		}
	}

	if(send_recv == MBOX_SEND)
	{
		for(int i=0;i<num_msg;i++)
		{
			uint64_t ret = hvif_mbox_send(core_id[i], mbox_id[i], msb32[i], lsb32[i]);
			if (ret != 0)
			{
				uint32_t msb = ret>>32;
				uint32_t lsb = ret & 0xFFFFFFFF;
				printf("Received from VSPA:%d, MBox:%d, MSB:0x%08x, LSB:0x%08x.\n", core_id[i], mbox_id[i], msb, lsb);
			}	
		}
	}
	else if(send_recv == MBOX_RECV)
	{
		for(int i=0;i<num_msg;i++)
		{
			uint64_t ret = hvif_mbox_recv(core_id[i], mbox_id[i]);
			if (ret != 0)
			{
				uint32_t msb = ret>>32;
				uint32_t lsb = ret & 0xFFFFFFFF;
				printf("Received from VSPA:%d, MBox:%d, MSB:0x%08x, LSB:0x%08x.\n", core_id[i], mbox_id[i], msb, lsb);
			}	
		}
	}

	hvif_reset();

    return 0;
}
