#!/bin/bash
# Copyright 2022-2025 NXP
#
# NXP Confidential. This software is owned or controlled by NXP and may only
# be used strictly in accordance with the applicable license terms. By expressly accepting
# such terms or by downloading, installing, activating and/or otherwise using
# the software, you are agreeing that you have read, and that you agree to
# comply with and are bound by, such license terms. If you do not agree to
# be bound by the applicable license terms, then you may not retain,
# install, activate or otherwise use the software.


test_tool_name="FR1_FR2_Test_Tool"
test_tool_version=5.1      #test tool version is the version for shell script, may be different with vspa image version.


#delete runtime config file generated by previous test
[ -f runtime_config.bak ] && rm runtime_config.bak
[ -f runtime_config.txt ] && cp runtime_config.txt runtime_config.bak
echo "#" > ./runtime_config.txt
echo "#" > ./command_list.sh
echo "#" > ./command_init.sh

source ./config.dat
source ./rfg_ctrl.sh

channels_start_fail()
{
	echo -e "Channels start failed\n"; rm runtime_config.txt; exit 1
}


print_usage()
{
echo
echo "usage ./channels_start.sh [ant_id] [txonly|rxonly] [sinad] [option8] [comp] [nl1c] [dcsx] [txdcsx] [rxdcsx] [0.5ms|1ms|2ms|5ms|10ms|20ms|40ms] [HRAM] [cpe|gnb] [mimo] [file] [nre=M|nrb=N] [search] [rx2host] [lb|rlbf|rlbt] [lphy|dfe] [hshake|txhshake|rxhshake] [nextlog] [pattern=X] [hwdcm|nhwdcm] [rt]"
echo "  ant_id: start specified antenna. If ant_id not specified, start all antennas/channels defined in config.dat"
echo "  txonly: start antennas with TX only, RX will be disabled."
echo "  rxonly: start antennas with RX only, TX will be disabled."
echo "  sinad:  for sinad test, in this test, only single tone will be used."
echo "  option8: test time domain waveform, iFFT/FFT will be bypassed."
echo "  comp:   test eCPRI compression/decompression enabled."
echo "  nl1c:   No NXP L1C, in this case users should use their own software to enable DCS after running channels_start.sh"
echo "  rx2host:   enable RX symbols sent to host RX symbol buffer. disabled by default in order to allow dumping which will occupy PCI bandwidth in RX direction"
echo "  lb:   LA12xx internal digital loopback from DAC to ADC. Only valid in HSDCS"
echo "  rlbf:   reverse loopback from RX frequency domain to TX frequency Domain. In RF view, signal sent from RX antenna to baseband is looped back to TX antenna."
echo "  dcsx:   specified DCS channel to be tested. x=0-5. can specify multiple DCS channels."
echo "  txdcsx: specified DCS channel to be tested for TX only. x=0-5. can specify multiple DCS channels."
echo "  rxdcsx: specified DCS channel to be tested for RX only. x=0-5. can specify multiple DCS channels."
echo "  0.5ms|1ms|2ms|5ms|10ms|20ms|40ms:    input waveform length"
echo "  HRAM:   input waveform is put on HRAM, this is useful when PCI bandwidth is not high enough, but waveform file size is limited to HRAM size"
echo "  cpe|gnb:TDD pattern works in CPE or gNB mode, for CPE downlink slots are receiving slots, uplink slots are transmitting slots"
echo "  mimo:   different input waveforms for different antennas, default is same waveform file for all antennas if mimo is not specified"
echo "  file:   input waveform filename, the file size should match the configured input waveform length"
echo "  nre=M|nrb=N:  specify num of RE or RB, one RB is 12 REs. Specify this option to use reduced bandwidth, such as nrb=24 will reduce bandwidth from 20Mhz to 10Mhz in scs30 use case."
echo "  search:   start with cell search mode. used only in UE/CPE"
echo "  hwdcm|nhwdcm:   enable or disable hardware decimation by 2 for HSADC"
echo "  rt:     Send real time symbol data from HighPHY. test tool will not load static waveform from file."
echo "          example:  ./channels_start.sh dcs2 dcs3                                  will test DCS channel 2 and 3 (DCS1-0,DCS1-1)."
echo "          example:  ./channels_start.sh txdcs2 rxdcs3                              will test TX on DCS channel 2 (DCS1-0) and RX on DCS channel 3 (DCS1-1)."
echo "          example:  ./channels_start.sh dcs4 option8 1ms HRAM waveform_file.bin    will test HSDCS0 with option8 1ms waveform length from HRAM and use specified waveform file"
echo
}

#measure tbgen clocks using vspa core clock. API measure_tbgen_clock_start/end vspa_core_id, call start first, after at least 1s, call end. result will be in tbgen1/2_freq
measure_tbgen_clock_start()
{
	vspa_core=$1
	vspa_tmr1=$(get_counter vspa $vspa_core)
	tbgen1_cnt1=$(get_counter tbgen1)
	tbgen2_cnt1=$(get_counter tbgen2)
}
measure_tbgen_clock_end()
{
	vspa_core=$1
	vspa_tmr2=$(get_counter vspa $vspa_core)
	tbgen1_cnt2=$(get_counter tbgen1)
	tbgen2_cnt2=$(get_counter tbgen2)
	
	vspa_tmr_inc=$((vspa_tmr2-vspa_tmr1))
	[ $vspa_tmr_inc = 0 ] && { echo ***ERROR: vspa core $vspa_core cycle counter is not enabled, failed to measure tbgen clock.; channels_start_fail; }
	vspa_tmr_inc_30720=$((vspa_tmr_inc/(vspa_core_clock/30720)))
	tbgen1_cnt_inc=$((tbgen1_cnt2-tbgen1_cnt1))
	tbgen2_cnt_inc=$((tbgen2_cnt2-tbgen2_cnt1))
	tbgen1_freq=$(((tbgen1_cnt_inc+vspa_tmr_inc_30720/2)/vspa_tmr_inc_30720*30720000))
	tbgen2_freq=$(((tbgen2_cnt_inc+vspa_tmr_inc_30720/2)/vspa_tmr_inc_30720*30720000))
}

enable_hsadc_fdd()
{
	get_hsadc_outof_low_power_mode
	./utils/memrw w 32 $((modembase_phy+0x1124450)) 0x100
	./utils/memrw w 32 $((modembase_phy+0x11244a0)) 0x100
}

stop_dcs_fdd()
(
	./utils/memrw w 32 $((modembase_phy+0x1120450)) 0
	./utils/memrw w 32 $((modembase_phy+0x11204a0)) 0
	./utils/memrw w 32 $((modembase_phy+0x11204F0)) 0
	./utils/memrw w 32 $((modembase_phy+0x1120540)) 0
	./utils/memrw w 32 $((modembase_phy+0x1124450)) 0
	./utils/memrw w 32 $((modembase_phy+0x11244a0)) 0
	put_hsadc_in_low_power_mode
)

#find DFE cores, 1=DFE core, 0=not DFE core
dfe_core=(0 0 0 0 0 0 0 0)    #dfe core is the master core which communicates with host.
slave_core=(0 0 0 0 0 0 0 0)  #slave core for each dfe core, valid 0-7, other values mean no slave core(1T1R on 1 core).
one_dfe_core=$INVALID_CORE
swversion_allcore=0
for ((i=0;i<NUM_CORES;i++))
do
	swversion=`./utils/memrw r 32 $((modembase_phy+0x1000000+i*0x4000+4))`
	((swversion_iden=swversion>>16))
	if [ $((swversion_iden)) -eq $((0xDFEF)) ];then
		((swversion_allcore=swversion_allcore|swversion))
		dfe_core[$i]=1
		one_dfe_core=$i
		((slave_core[$i]=(swversion>>13)&7))
	fi
done
[ $((one_dfe_core)) -ge $INVALID_CORE ] && { echo ***ERROR: VSPA images are not $test_tool_name images.; echo; channels_start_fail; }
((flag_dfe_initialized=(swversion_allcore>>12)&1))
vspa_image_version=`printf "0x%x" $((swversion_allcore&0xFFF))`
revision=$((($vspa_image_version >> 0) & 0xF))
ver_min=$((($vspa_image_version >> 4) & 0xF))
ver_maj=$((($vspa_image_version >> 8) & 0xF))

source ./check_dfe_cap_core_map.sh  #include here after MAX_NUM_1R_IN_CORE is resolved

e200_cmd_tool=gul_refapp
if [ -f /sys/yami/yami_version ];then
	cat /sys/yami/yami_version | grep sdk3
	[ $? -eq 0 ] && e200_cmd_tool=gul_cli
fi

pci_bw_req_total=0
next_HRAMaddr_phy=$HRAMaddr_phy
next_FRAMaddr_phy=$((FRAMaddr_phy+FRAM_size-128*1024)) #the last 128KB FRAM used for test tool
obs_buffer_phy=0; obs_buffer_size=0;
obs_chan_enable=0
ant_selected=(0 0 0 0 0 0)
ant_order=(0 1 2 3 4 5)
ant_sel_ls=0; ant_sel_hs=0
arg_dcs=(0 0 0 0 0 0)
arg_dcsen=0
txonly=0
rxonly=0
txrestart=0
rxrestart=0
restart=0
loopback=0
force_ru=0
idle=0             #used to not route TX/RX host symbols to FRAM and not injecting TX test vector, in order to see ISC is working stably without DDR access
sinad=0
fast=0
option8_cfg=$option8
warning_list=""
test_vector_on_hram=0
invecfile_arg=0
mimo=0
nrb=0
cell_state=$CELL_STATE_NORMAL
norx2host=1; lphy=0; dfe_only=0
txhshake=0; rxhshake=0
cpe=0                      #LA12xx device is gNB by default
extlog=0
use_specified_pattern=0; specified_pattern=(0)
hwdcm=0; arg_hwdcm=0; arg_nhwdcm=0
dbg=0
wvpd=0; sym_buf_onchip=0
rxinj_file=""
size_dump=0; size_inject=0
rt=0
rloopback_freq=0; rloopback_time=0
no_wv_load=0

arg_parse()
{
	arg=$1 #; ([ $arg = 0 ] || [ $arg = 1 ] || [ $arg = 2 ] || [ $arg = 3 ] || [ $arg = 4 ] || [ $arg = 5 ]) && arg=dcs$arg
	arg0_4=${arg:0:5}; arg5=${arg:5}; arg0_2=${arg:0:3}; arg3=${arg:3}
	if [ $arg = txonly ]; then							txonly=1
	elif [ ${arg:0:7} = pattern ]; then					use_specified_pattern=1; eval specified_pattern=('$'{$arg[@]}); pattern_len=${#specified_pattern[@]}
														([ $pattern_len = 0 ] || ([ $((pattern_len%6)) -ne 0 ] && [ $((pattern_len%4)) -ne 0 ])) && { echo -e "***ERROR: Specified pattern $arg does not exist\n"; channels_start_fail; }
														echo specified_pattern="(${specified_pattern[@]})"
	elif [ $arg = rxonly ]; then							rxonly=1
	elif [ $arg = txrestart ]; then						txrestart=1; restart=1
	elif [ $arg = rxrestart ]; then						rxrestart=1; restart=1
	elif [ $arg = restart ]; then							txrestart=1; rxrestart=1; restart=1
	elif [ $arg = ru ]; then								force_ru=1; echo Testing ISC using RU mode. #force ISC to RU
	elif [ $arg = idle ]; then							idle=1
	elif ([ $arg = sinad ] || [ $arg = SINAD ]); then		idle=1; sinad=1
	elif ([ $arg = loopback ] || [ $arg = lb ]); then		loopback=1
	elif [ $arg = rlbf ]; then								rloopback_freq=1
	elif [ $arg = rlbt ]; then								rloopback_time=1
	elif [ $arg = option8 ]; then							option8_cfg=1
	elif [ $arg = comp ]; then							ecpri_comp_decomp_enable=1
	elif [ $arg = nl1c ]; then							use_nxp_l1c=0
	elif [ $arg = fdd ]; then							tx_fdd=1; rx_fdd=1
	elif [ $arg = tdd ]; then							tx_fdd=0; rx_fdd=0
	elif [ $arg = txfdd ]; then							tx_fdd=1
	elif [ $arg = rxfdd ]; then							rx_fdd=1
	elif [ $arg = txtdd ]; then							tx_fdd=0
	elif [ $arg = rxtdd ]; then							rx_fdd=0
	elif [ $arg = rt ]; then							rt=1
	elif [ $arg = fast ]; then							fast=1
	elif [ $arg = hwdcm ]; then							hwdcm=1; arg_hwdcm=1
	elif [ $arg = nhwdcm ]; then						hwdcm=0; arg_nhwdcm=1
	elif [ ${arg:0:4} = nre= ]; then					nre=$(($(echo $arg | cut -d "=" -f2))); nrb=$((nre/12)); [ $((nrb*12)) -ne $nre ] && { echo -e "***ERROR: nre must be multiple of 12\n"; channels_start_fail; }
	elif [ ${arg:0:4} = nrb= ]; then					nrb=$(($(echo $arg | cut -d "=" -f2)))
	elif [ ${arg:0:3} = nrb ]; then						nrb=$(($(echo $arg | cut -d "b" -f2)))
	elif [ ${arg:0:6} = rxinj= ]; then					rxinj_file=$(echo $arg | cut -d "=" -f2); #rxonly=1;
														[ -f $rxinj_file ] || { echo File $rxinj_file does not exist; echo; print_usage; exit 1; }
	elif [ $arg = 0 ]; then								ant_order[ant_sel_ls]=$arg; ((ant_sel_ls++)); ant_selected[0]=$BITMASK_ANT_ENABLE_TRX; echo Enable ant 0
	elif [ $arg = 1 ]; then								ant_order[ant_sel_ls]=$arg; ((ant_sel_ls++)); ant_selected[1]=$BITMASK_ANT_ENABLE_TRX; echo Enable ant 1
	elif [ $arg = 2 ]; then								ant_order[ant_sel_ls]=$arg; ((ant_sel_ls++)); ant_selected[2]=$BITMASK_ANT_ENABLE_TRX; echo Enable ant 2
	elif [ $arg = 3 ]; then								ant_order[ant_sel_ls]=$arg; ((ant_sel_ls++)); ant_selected[3]=$BITMASK_ANT_ENABLE_TRX; echo Enable ant 3
	elif [ $arg = 4 ]; then								ant_order[ant_sel_hs+4]=$arg; ((ant_sel_hs++)); ant_selected[4]=$BITMASK_ANT_ENABLE_TRX; echo Enable ant 4
	elif [ $arg = 5 ]; then								ant_order[ant_sel_hs+4]=$arg; ((ant_sel_hs++)); ant_selected[5]=$BITMASK_ANT_ENABLE_TRX; echo Enable ant 5
	elif ([ $arg0_2 = dcs ] && [ $((arg3)) -le 5 ]); then	((arg_dcsen++)); arg_dcs[arg3]=$BITMASK_ANT_ENABLE_TRX; echo Enable TX and RX on dcs$((arg3)).
	elif ([ $arg0_4 = txdcs ] && [ $((arg5)) -le 5 ]); then	((arg_dcsen++)); ((arg_dcs[arg5]=arg_dcs[arg5]|$BITMASK_ANT_ENABLE_TX)); echo Enable TX only on dcs$((arg5)).
	elif ([ $arg0_4 = rxdcs ] && [ $((arg5)) -le 5 ]); then	((arg_dcsen++)); ((arg_dcs[arg5]=arg_dcs[arg5]|$BITMASK_ANT_ENABLE_RX)); echo Enable RX only on dcs$((arg5)).
	elif ([ $arg = 0.5ms ] || [ $arg = .5ms ]); then		input_waveform_len[0]=0.5; input_waveform_len[1]=0.5
	elif [ $arg = 1ms ]; then								input_waveform_len[0]=1; input_waveform_len[1]=1
	elif [ $arg = 2ms ]; then								input_waveform_len[0]=2; input_waveform_len[1]=2
	elif [ $arg = 5ms ]; then								input_waveform_len[0]=5; input_waveform_len[1]=5
	elif [ $arg = 10ms ]; then							input_waveform_len[0]=10; input_waveform_len[1]=10
	elif [ $arg = 20ms ]; then							input_waveform_len[0]=20; input_waveform_len[1]=20
	elif [ $arg = 40ms ]; then							input_waveform_len[0]=40; input_waveform_len[1]=40
	elif ([ $arg = HRAM ] || [ $arg = hram ]); then			test_vector_on_hram=1
	elif ([ $arg = cpe ] || [ $arg = CPE ] || [ $arg = UE ] || [ $arg = ue ]); then	cpe=1
	elif [ $arg = search ]; then							cell_state=$CELL_STATE_SEARCH
	elif [ $arg = rx2host ]; then							norx2host=0
	elif [ $arg = lphy ]; then							lphy=1; use_nxp_l1c=0
	elif [ $arg = dfe ]; then							dfe_only=1
	elif [ $arg = txhshake ]; then						txhshake=1
	elif [ $arg = rxhshake ]; then						rxhshake=1
	elif [ $arg = hshake ]; then						txhshake=1; rxhshake=1
	elif [ $arg = nextlog ]; then							extlog=0
	elif [ $arg = extlog ]; then							extlog=1
	elif [ $arg = dbg ]; then								dbg=1
	elif [ $arg = wvpd ]; then								wvpd=1;
	elif [ $arg = onchip ]; then							sym_buf_onchip=1;
	elif ([ $arg = gnb ] || [ $arg = gNB ] || [ $arg = BS ] || [ $arg = bs ]); then	cpe=0
	elif [ $arg = mimo ]; then							mimo=1
	else												invecfile_arg=$arg; [ -f $invecfile_arg ] || { echo Illegal Argument $arg, or file $arg does not exist; echo; print_usage; exit 1; }
	fi
}

for i in "$@"
do
	arg_parse $i
done

[ $rloopback_freq = 1 ] && { norx2host=0; no_wv_load=1; }
[ $rloopback_time = 1 ] && { idle=1; hwdcm=0; arg_nhwdcm=1; no_wv_load=1; }   #DAC ADC sampling rate should be same for reverse loopback time domain, freq domain processing set to idle

source ./boot_vspa_log.txt
echo "$vspa_image_folder_name" | grep ADvspa_images_LS.4T4R_100M_30K_491_245_TDDFDD_ISC
if [ $? = 0 ];then
	sym_buf_onchip=1  #for ISC, rx sym buffers are on onchip memory
	[ $((txonly|rxonly)) -eq 0 ] && { echo Current VSPA image supports TDD only, set TDD mode.; tx_fdd=0; rx_fdd=0; }
fi
echo "$vspa_image_folder_name" | grep MEvspa_images_LS.1T1R.T4x_25M_60K_122_122_TDDFDD_LA93
[ $? = 0 ] && { echo Current VSPA image supports DFE only, set DFE mode.; dfe_only=1; sym_buf_onchip=1; }
echo "$vspa_image_folder_name" | grep MEvspa_images_HS.1T1R_1600M_120K_1966_1966_TDDFDD
[ $? = 0 ] && { hwdcm=0; arg_nhwdcm=1; test_vector_on_hram=1; input_waveform_len[0]=0.5; input_waveform_len[1]=0.5; }

size_inject_rx=0
if [ "$rxinj_file" != "" ];then
if [ $((vspa_image_version)) -ge $((0x482)) ];then
	size_inject_rx=$(stat --format=%s $rxinj_file)
else
	echo ***ERROR: RX injection is not supported in version older than v482; channels_start_fail;
fi
fi

addr_inject_rx=$ddr_malloc_cur
ddr_malloc_cur=`printf 0x%x $((ddr_malloc_cur + size_inject_rx))`
if [ $size_inject_rx -ne 0 ];then
	loadfile `phy2vir $addr_inject_rx` $rxinj_file
fi

if [ $vspa_dev_type = LA9310 ];then
m4_version=`./utils/memrw r 32 $hif_vir`
m4_version=`HEX $(( ((m4_version&0xFFFF)<<4)|((m4_version>>16)&0xF) ))`
required_m4_version=0x00041
if [ $((m4_version)) -lt $((required_m4_version)) ];then
	str="***WARNING: M4 image version $m4_version can not work with current version of test tool, please update M4 image to $required_m4_version or newer"
	echo -e "$str"; warning_list="$warning_list$str\n"
fi
cpe=1                      #DFE on LA9310 is UE/CPE by default
[ -f /usr/bin/dpdk-dfe_app ] || { echo "***ERROR: missing /usr/bin/dpdk-dfe_app. You are using old BSP, upgrade to BSP 0.4 or above, or build /usr/bin/dpdk-dfe_app by yourself."; channels_start_fail; }
fi

./utils/memrw w 32 $test_tool_env_cell_state $cell_state #set cell state to env

if [ $cell_state = $CELL_STATE_SEARCH ];then
	[ $cpe = 0 ] && { echo ***ERROR: Basestation mode does not support cell search; channels_start_fail; }
	[ $((tx_fdd|rx_fdd)) -ne 0 ] && rxonly=1
fi

[ $((ant_sel_ls+ant_sel_hs+arg_dcsen)) -eq 0 ] && ant_selected=($BITMASK_ANT_ENABLE_TRX $BITMASK_ANT_ENABLE_TRX $BITMASK_ANT_ENABLE_TRX $BITMASK_ANT_ENABLE_TRX $BITMASK_ANT_ENABLE_TRX $BITMASK_ANT_ENABLE_TRX)

for((i=0;i<NUM_ANTS;i++))
do
	((DCSchan[i]=(4-DCSchan[i])&3))         #convert 0,1,2,3 to 0,3,2,1 which stands for disabled,tx rx all enabled, tx only, rxonly
done

if [ $arg_dcsen != 0 ];then
	txant_idx=0; rxant_idx=0
	ant_map_tx=(0 1 2 3 4 5); ant_map_rx=(0 1 2 3 4 5)
	for((i=0;i<NUM_ANTS;i++))
	do
		[ $i = 4 ] && { txant_idx=4; rxant_idx=4; }
		((DCSchan[i]=arg_dcs[i]))
		if [ $((DCSchan[i]&BITMASK_ANT_ENABLE_TX)) -ne 0 ];then
			((ant_map_tx[ant_order[txant_idx]]=i))
			((ant_selected[ant_order[txant_idx]]=ant_selected[ant_order[txant_idx]] | $BITMASK_ANT_ENABLE_TX))
			((txant_idx++))
		fi
		if [ $((DCSchan[i]&BITMASK_ANT_ENABLE_RX)) -ne 0 ];then
			((ant_map_rx[ant_order[rxant_idx]]=i))
			((ant_selected[ant_order[rxant_idx]]=ant_selected[ant_order[rxant_idx]] | $BITMASK_ANT_ENABLE_RX))
			((rxant_idx++))
		fi
		ant_remap=1
	done
fi
[ $ant_remap = 0 ] && {	ant_map_tx=(0 1 2 3 4 5); ant_map_rx=(0 1 2 3 4 5); }

if [ $fast = 0 ];then
echo
echo "Test Tool name          :   $test_tool_name"
echo "Test Tool script Version:   $test_tool_version"
echo "VSPA image Version      :   $ver_maj.$ver_min.$revision"
read board_name < /proc/device-tree/model
echo "Board Name              :  " "$board_name"
print_addr_mapping
fi

for ((n=0;n<${#known_iqswap_list[@]};n=n+13))
do
	if [ "$board_name" = "${known_iqswap_list[n]}" ];then
		for ((i=0;i<NUM_ANTS;i++))
		do 
			iqswap_tx[i]=${known_iqswap_list[n+1+i]};iqswap_rx[i]=${known_iqswap_list[n+7+i]}
		done
		[ $fast = 0 ] && echo "Update IQ swap config due to board errata: iqswap_tx=(${iqswap_tx[@]}), iqswap_rx=(${iqswap_rx[@]})"; 
		break;
	fi
done
echo

lsdiv2=`./utils/memrw r 32 $test_tool_env_lsdiv2`
hsdiv2=`./utils/memrw r 32 $test_tool_env_hsdiv2`
bwdiv=`./utils/memrw r 32 $test_tool_env_bwdiv`



vspa_mbox_ifsend $one_dfe_core $host_vspa_mbox_id 0x4E000000 0; [ $msg_recv_flag = 0 ] && vspa_mbox_ifrecv $one_dfe_core $host_vspa_mbox_id
[ $msg_recv_flag = 0 ] && { echo "***ERROR: No response from core $one_dfe_core for ANT-CORE mapping msg."; channels_start_fail; }
ant_core_map_tx=$msg_recv_lsb32; ant_core_map_rx=$msg_recv_msb32
([ $vspa_dev_type = LA9310 ] && [ $tx_fdd = 1 ]) && ant_core_map_rx=$((ant_core_map_rx | 0xF0 ))   #mask 2nd R if it's FDD as LA9310 only support 1T1R for FDD

anttx=(0xF 0xF 0xF 0xF 0xF 0xF)    #which TX core is for each ant
antrx=(0xF 0xF 0xF 0xF 0xF 0xF)
coretx_tr0=(0xF 0xF 0xF 0xF 0xF 0xF 0xF 0xF)  #which ant is for each core, max 2T2R per core.
corerx_tr0=(0xF 0xF 0xF 0xF 0xF 0xF 0xF 0xF)
coretx_tr1=(0xF 0xF 0xF 0xF 0xF 0xF 0xF 0xF)
corerx_tr1=(0xF 0xF 0xF 0xF 0xF 0xF 0xF 0xF)
for ((ant=0;ant<NUM_ANTS;ant++))
do
txcore=$((($ant_core_map_tx >> $((4*$ant))) & 0xF))
rxcore=$((($ant_core_map_rx >> $((4*$ant))) & 0xF))
anttx[$ant]=$txcore
antrx[$ant]=$rxcore
if [ $txcore -lt 8 ];then
	if [ $((coretx_tr0[$txcore])) -eq $((0xF)) ];then
		coretx_tr0[$txcore]=$ant
	else
		coretx_tr1[$txcore]=$ant
	fi
fi
if [ $rxcore -lt 8 ];then
	if [ $((corerx_tr0[$rxcore])) -eq $((0xF)) ];then
		corerx_tr0[$rxcore]=$ant
	else
		corerx_tr1[$rxcore]=$ant
	fi
fi
done


fr1_used=0
fr2_used=0

tidcore=(0 0 0 0 0 0 0 0)   #temp var, used to calculate trid (0 or 1)
ridcore=(0 0 0 0 0 0 0 0)
#num_TR_per_core=(0 0 0 0 0 0 0 0)   #max number of T or R or TR in each core.
num_T_LS=0; num_R_LS=0; num_T_HS=0; num_R_HS=0
num_T_LS_enabled=0; num_R_LS_enabled=0; num_T_HS_enabled=0; num_R_HS_enabled=0
tidant=(0 0 0 0 0 0)        #get tid from ant_id.
ridant=(0 0 0 0 0 0)
for ((ant=0;ant<NUM_ANTS;ant++))
do
	txcore=${anttx[$ant]}
	if [ $txcore -ne $((0xF)) ]; then
	tidant[$ant]=${tidcore[$txcore]}
	tidcore[$txcore]=$((${tidcore[$txcore]} + 1))
	if [ $ant -lt 4 ]; then
		fr1_used=1
		((num_T_LS++))
	else
		fr2_used=1
		((num_T_HS++))
	fi
	fi
	
	rxcore=${antrx[$ant]}
	if [ $rxcore -ne $((0xF)) ]; then
	ridant[$ant]=${ridcore[$rxcore]}
	ridcore[$rxcore]=$((${ridcore[$rxcore]} + 1))
	if [ $ant -lt 4 ]; then
		fr1_used=1
		((num_R_LS++))
	else
		fr2_used=1
		((num_R_HS++))
	fi
	fi
done
[ $((num_T_LS+num_T_HS)) = $NUM_ANTS ] && { sinad=1; idle=1; }
[ $fast = 0 ] && echo -e "Maximum Capacity: Num channels supported: $num_T_LS TX on LS,  $num_R_LS RX on LS, $num_T_HS TX on HS, $num_R_HS RX on HS\n"

get_chan_para $(((1-fr1_used)*4)) 0xFF; [ $? -ne 0 ] && channels_start_fail #get channel parameters

if [ $flag_dfe_initialized = 0 ];then   #restart handling
	rxrestart=0; txrestart=0			#this is not a real restart, but just a first time start after boot.
	./utils/memset $test_tool_env_tx_scaling_input $NUM_ANTS 100  #set only at first time start
	./utils/memset $test_tool_env_tx_scaling_output $NUM_ANTS 100
	./utils/memset $test_tool_env_rx_scaling $NUM_ANTS 100
	boot_flag=`./utils/memrw r 32 $test_tool_env_boot_vspa_ind`
	if [ $((boot_flag)) -ne $((0x1234abcd)) ];then
		str="***WARNING: VSPA images were not booted by ./boot_vspa.sh, critical issues may occur during test.\n              Suggest to always boot VSPA images with ./boot_vspa.sh"
		echo -e "$str"; warning_list="$warning_list$str\n"
	fi
elif [ $((txrestart|rxrestart)) -eq 0 ];then
	if [ -f runtime_config.bak ];then
		cp runtime_config.bak runtime_config.txt   #restore the runtime config file
		echo -e "\nChannels already started/initialized. No need to start again. To restart channels, run ./channels_start.sh restart\n"
		exit 1
	else
		echo -e "\n***ERROR: Channels already started, but runtime config file runtime_config.txt does not exist, run channels_start.sh restart\n"
		channels_start_fail
	fi
else
	echostr="Restarting VSPA cores."
	tx_fdd_pre=`./utils/memrw r 32 $test_tool_env_fdd_mode_pre` #get previous fdd mode.
	
	if ([ $((tx_fdd_pre)) = 0 ] && [ $vspa_dev_type = LA9310 ]);then
		dpdk-dfe_app -c "tdd stop"  #stop TDD first if previous mode is TDD, and do not restart vspa
	else
	for ((i=0;i<NUM_CORES;i++)) #restart cores
	do
		if [ $((dfe_core[i])) -eq 1 ];then
			swversion=`./utils/memrw r 32 $((modembase_phy+0x1000000+i*0x4000+4))`
			if [ $(((swversion>>12)&1)) -eq 1 ];then
				echostr="${echostr} $i "   #restart each core if it's initialized
				dfe_mode_msb=$((`./utils/memrw r 32 $((test_tool_env_dfe_mode_msg+i*8+0))` | 0x00300000))  #set restart bits
				dfe_mode_lsb=`./utils/memrw r 32 $((test_tool_env_dfe_mode_msg+i*8+4))` 
				echo vspa_mbox send $i $host_vspa_mbox_id `HEX $dfe_mode_msb` $dfe_mode_lsb
				vspa_mbox_ifsend $i $host_vspa_mbox_id $dfe_mode_msb $dfe_mode_lsb; 
				sleep 0.1
				[ $msg_recv_flag = 0 ] && vspa_mbox_ifrecv $i $host_vspa_mbox_id
				([ $msg_recv_flag = 0 ] || ([ $((msg_recv_msb32&0xFF000000)) -ne $((0x0F000000)) ] && [ $((msg_recv_msb32)) -ne $((0xF1000000)) ])) && { echo "***ERROR: VSPA core $i did not respond to restart msg."; channels_start_fail; }
				flag_dfe_initialized=$(((`./utils/memrw r 32 $((modembase_phy+0x1000000+i*0x4000+4))` >>12)&1))
				[ $flag_dfe_initialized -ne 0 ] && { echo -e "***ERROR: VSPA core $i restart failure, can not enter initialization stage\n"; channels_start_fail; }
				echo Core $i restarted from initialized stage to expected un-initialized state.
				[ $dbg = 1 ] && { ./utils/view_vspa_reg.sh $((slave_core[i])) dma; ./utils/view_vspa_reg.sh $((slave_core[i])) axiq; }
			fi
		fi
	done
	echo $echostr
	fi
	
	echo Stopping DCS...
	echo Restarting from ${tag_tddfdd[tx_fdd_pre]} to ${tag_tddfdd[tx_fdd]}
	if [ $vspa_dev_type = LA9310 ];then
	[ $((tx_fdd_pre)) = 1 ] && dpdk-dfe_app -c "fdd stop"
	else
	[ $((tx_fdd_pre)) = 0 ] && { echo $e200_cmd_tool -c "l1c stop"; $e200_cmd_tool -c "l1c stop"; }
	sleep 0.5
	echo stop_dcs_fdd; stop_dcs_fdd #in case LS is TDD and HS is FDD this is needed.
	fi

	if [ $dbg = 1 ];then
	echo VSPA DMA and AXIQ status after tx rx allowed disabled:
	./utils/view_vspa_reg.sh 0 dma
	./utils/view_vspa_reg.sh 0 axiq
	fi
	
	log=`check_error`
	rxrestart=0; txrestart=0
	
	if [ $type_ru -eq 0 ]; then
	if [ $fr1_used = 1 ];then  #restart HighPHY TX/RX cores in case of ISC
	txcore=6
	rxcore=4
	else
	txcore=2
	rxcore=0
	fi
	
	((dfe_mode_msb=0x0E30001C|(tx_fdd<<12)|(rx_fdd<<13)))
	dfe_mode_lsb=0
	dfe_mode_msb=`printf "0x%08x" $dfe_mode_msb`
	
	echo
	echo Restart HighPHY TX RX cores:

	echo "vspa_mbox send $txcore $host_vspa_mbox_id $dfe_mode_msb $dfe_mode_lsb "
	vspa_mbox_ifsend $txcore $host_vspa_mbox_id $dfe_mode_msb $dfe_mode_lsb
	echo "vspa_mbox send $rxcore $host_vspa_mbox_id $dfe_mode_msb $dfe_mode_lsb "
	vspa_mbox_ifsend $rxcore $host_vspa_mbox_id $dfe_mode_msb $dfe_mode_lsb
	fi
fi

#the following is a workaround to set up IQFLOOD PCI window for the BSP bug in old BSP version
#if [ $vspa_dev_type = LA9310 ];then
#./utils/memrw w 32 0x000000001b400900 3
#pci_win3_enable=`./utils/memrw r 32 0x000000001b400908`
#if [ $((pci_win3_enable)) -ne $((0x80000000)) ];then
#./utils/memrw w 32 0x000000001b40090c 0xb0001000
#./utils/memrw w 32 0x000000001b400914 0xbd000fff 
#./utils/memrw w 32 0x000000001b400918 0x96400000
#./utils/memrw w 32 0x000000001b400908 0x80000000
#echo PCI Outbound Window 3 is configured for IQFLOOD by test tool as below
#
#else
#echo PCI Outbound Window 3 is already configured by BSP as below:
# 
#fi
#./utils/loadmem null 0x1b400900 -r 32 
#fi



if [ $vspa_dev_type = LA9310 ];then  #loopback handling
	if [ $loopback = 1 ];then
	echo dpdk-dfe_app -c "axiq_lb enable"
	echo dpdk-dfe_app -c \"axiq_lb enable\" >> ./command_init.sh
	dpdk-dfe_app -c "axiq_lb enable"
	echo Clearing all IQSWAP due to AXIQ Digital Loopback.
	iqswap_tx=(${ANTS_ARR_INIT[@]}); iqswap_rx=(${ANTS_ARR_INIT[@]});
	fi
else
	if [ $loopback = 1 ];then
		hsdcs_loopback_enable
		echo "HS AXIQ/DCS is set to LOOPBACK mode."
		echo Clearing HSDCS IQSWAP due to AXIQ Digital Loopback.
		iqswap_rx[4]=0; iqswap_rx[5]=0 #remove IQSWAP in loopback mode
	else
		hsdcs_loopback_disable
	fi
fi


#build TDD pattern msg from config.dat
./utils/memrw w 32 $test_tool_env_fdd_mode_pre $((tx_fdd|dcsfdd))  #keep current fdd mode to env

dpd_model_get_para
if [ $((dpd_model_id)) -eq 7 ]; then
	flag_deqec=1
else
	flag_deqec=0
fi

pattern_msg0=0; pattern_msg1=0
l1c_cfg_msb=0; l1c_cfg_lsb=0
if [ $((tx_fdd&rx_fdd)) = 0 ];then
if [ ${#pattern[@]} -ge 6 ];then
	l1c_cfg_lsb=$(( ${pattern[0]} + (${pattern[4]} << 4) +  (${pattern[1]} << 8) + (${pattern[2]} << 12) + (${pattern[5]} << 16) +  (${pattern[3]} << 20) ))
	pattern_msg0=$((0x01000000 + l1c_cfg_lsb ))
	pattern_msg1=0x12000000
fi

if [ ${#pattern[@]} -eq 12 ];then
	l1c_cfg_msb=$(( ${pattern[6]} + (${pattern[10]} << 4) + (${pattern[7]} << 8) + (${pattern[8]} << 12) + (${pattern[11]} << 16) + (${pattern[9]} << 20) ))
	pattern_msg0=$((0x01000000 + pattern_msg0)) #two patterns.
	pattern_msg1=$((0x12000000 + l1c_cfg_msb ))
fi

if [ ${#pattern[@]} -eq 4 ];then
[ $vspa_dev_type = LA12xx ] && { echo -e "***ERROR: minislot is currently not supported on LA12xx\n"; channels_start_fail; }
fi

if [ $vspa_dev_type = LA12xx ];then
l1c_cfg_msb=$(( l1c_cfg_msb | (0x81<<24) ))
l1c_cfg_lsb=$(( l1c_cfg_lsb | ((ul_dl_gap/100)<<24) ))
echo L1C CONFIG TDD PATTERN mailbox msg sent by VSPA core $one_dfe_core mailbox $((1-host_vspa_mbox_id )) MSB `HEX $l1c_cfg_msb` LSB `HEX $l1c_cfg_lsb`
vspa_mbox_ifsend $one_dfe_core $host_vspa_mbox_id $l1c_cfg_msb $l1c_cfg_lsb
echo "./utils/vspa_mbox send $one_dfe_core $host_vspa_mbox_id $l1c_cfg_msb $l1c_cfg_lsb" >> ./command_init.sh
fi

pattern_msg0=`HEX $pattern_msg0`; pattern_msg1=`HEX $pattern_msg1`
fi

if [ $type_ru -eq $((0)) ]; then
	bypass_handshake_tx=0
	bypass_handshake_rx=0
	no_rx_sym_to_host=0
else
	bypass_handshake_tx=$((1-txhshake)) #for RU, bypass RX handshake.
	bypass_handshake_rx=$((1-rxhshake)) #for RU, bypass RX handshake. 
	no_rx_sym_to_host=$((norx2host<<DFE_MODE_NO_RX_SYM_TO_HOST_IDX)) #DFE_MODE_NO_RX_SYM_TO_HOST   #for RU, set No rx symbol to host to save PCI bandwidth for test purpose
fi

measure_tbgen_clock_start $one_dfe_core
txdcs_ls=0
txdcs_hs=0
rxdcs_ls=0
rxdcs_hs=0
scs_ls=0
scs_hs=0
yesno=0
invecfile_ori=(${ANTS_ARR_INIT[@]}); invecfile_cur=(${ANTS_ARR_INIT[@]}); invecsize_exp=(${ANTS_ARR_INIT[@]})
ant_enable=(${ANTS_ARR_INIT[@]});    dcs_enable=(${ANTS_ARR_INIT[@]});    sinad_enable_arr=(${ANTS_ARR_INIT[@]})
option8_tx=(${ANTS_ARR_INIT[@]});    option8_rx=(${ANTS_ARR_INIT[@]})
bbsps_tx=(${ANTS_ARR_INIT[@]});      bbsps_rx=(${ANTS_ARR_INIT[@]})
axiqsps_tx=(${ANTS_ARR_INIT[@]});    axiqsps_rx=(${ANTS_ARR_INIT[@]})
pci_bw_req=(${ANTS_ARR_INIT[@]})
sym_size_per_ant=(${ANTS_ARR_INIT[@]}); max_sym_size_per_ant=(${ANTS_ARR_INIT[@]})
upsampling_ratio_per_ant=(${ANTS_ARR_INIT[@]}); block_size_per_ant=(${ANTS_ARR_INIT[@]})

trace_log_buf_base=`HEX $ddr_malloc_cur`
trace_log_buf_size_per_core=$((128*1024))
trace_log_buf_size=$((NUM_CORES*trace_log_buf_size_per_core))
./utils/memset `phy2vir $trace_log_buf_base` $((trace_log_buf_size/4)) 0
ddr_malloc_cur=$((ddr_malloc_cur+trace_log_buf_size))

sym_buf_size_in_queue=$((POINTS_FFT*4*baseband_upsampling_rate))

num_sym_in_queue_tx=28
tx_sym_queue_base=$ddr_malloc_cur
tx_sym_queue_size=$((sym_buf_size_in_queue*num_sym_in_queue_tx/14*15))   #time domain size is 15/14 off FFT size because of CP
./utils/memset `phy2vir $tx_sym_queue_base` $((tx_sym_queue_size/4)) 0
ddr_malloc_cur=`size_align $((ddr_malloc_cur+tx_sym_queue_size)) 4096`

if [ $sym_buf_onchip = 0 ];then
num_sym_in_queue_rx=28
rx_sym_queue_base=`HEX $ddr_malloc_cur`
rx_sym_queue_size=$((sym_buf_size_in_queue*num_sym_in_queue_rx*(num_R_LS+num_R_HS)/14*15))
./utils/memset `phy2vir $rx_sym_queue_base` $((rx_sym_queue_size/4)) 0
ddr_malloc_cur=`size_align $((ddr_malloc_cur+rx_sym_queue_size)) 4096`

else
num_sym_in_queue_rx=2
rx_sym_queue_base=$next_HRAMaddr_phy
rx_sym_queue_size=$((sym_buf_size_in_queue*num_sym_in_queue_rx))
./utils/memset `phy2vir $rx_sym_queue_base` $((rx_sym_queue_size/4)) 0
next_HRAMaddr_phy=`size_align $((next_HRAMaddr_phy+rx_sym_queue_size)) 4096`
fi

########################## allocate cell tracking ext buffer ##############################
celltrack_extbuf_size=8192
if [ $vspa_dev_type = LA9310 ];then
	celltrack_extbuf_base=$next_HRAMaddr_phy
	next_HRAMaddr_phy=`size_align $((next_HRAMaddr_phy+celltrack_extbuf_size)) 4096`
else
	celltrack_extbuf_base=$next_FRAMaddr_phy
	next_FRAMaddr_phy=$((next_FRAMaddr_phy+celltrack_extbuf_size))
fi

celltrack_pssref_file=./test_vectors/pss_id1_ref256.bin
celltrack_params_file=./test_vectors/params.bin
if [ -f $celltrack_pssref_file ];then
	addr_vir=`phy2vir $((celltrack_extbuf_base+3072+512))`
	loadfile $addr_vir $celltrack_pssref_file
	echo "Loading cell tracking PSS Ref from file $celltrack_pssref_file to address $addr_vir"
else
	str="***WARNING: Cell Tracking PSS Ref file $celltrack_pssref_file does not exist."
	echo $str; warning_list="$warning_list$str\n"
fi
if [ -f $celltrack_params_file ];then
	addr_vir=`phy2vir $((celltrack_extbuf_base+3072+256))`
	loadfile $addr_vir $celltrack_params_file
	echo "Loading cell tracking params from file $celltrack_params_file to address $addr_vir"
else
	str="***WARNING: Cell Tracking params data file $celltrack_params_file does not exist."
	echo $str; warning_list="$warning_list$str\n"
fi



tv_malloc_cur=$((next_HRAMaddr_phy*test_vector_on_hram+ddr_malloc_cur*(1-test_vector_on_hram)))
addr_tx_test_vector=$tv_malloc_cur;
addr_tx_wv=(${ANTS_ARR_INIT[@]})
invec_addr_cur_backup=0; invecsize_backup=0; invecfile_backup=0
print_msg=""
one_enabled_dfe_core=0
[ $((sinad+dfe_only+rt)) -ne 0 ] && no_wv_load=1

	for ((core=0;core<NUM_CORES;core++))
	do
		txant=${coretx_tr0[$core]}; txant_ori=$txant; rxant=${corerx_tr0[$core]}; rxant_ori=$rxant
		txant2=${coretx_tr1[$core]}; rxant2=${corerx_tr1[$core]}
		([ $((txant)) -eq $((0xF)) ] && [ $((rxant)) -eq $((0xF)) ]) && continue #echo No TX and RX configured in core $core
		
		if ([ $num_T_LS -ne 0 ] && [ $tx_fdd = 0 ] && [ $((txant&rxant)) -ge 4 ]);then	#when LS is TDD, HS will be configured as FDD due to l1c doesn't support both LS+HS in TDD.
			((dfe_mode_msb=(cpe<<10)|(1<<12)|(1<<13)))   #these 3 configurations must be put here before get_chan_para() is called
		else
			((dfe_mode_msb=(cpe<<10)|(tx_fdd<<12)|(rx_fdd<<13)))   #these 3 configurations must be put here before get_chan_para() is called
		fi
		
		dfe_mode_lsb=$((nrb<<24)); 
		if [ $((txant)) -eq $((0xF)) ];then
			((dfe_mode_msb=dfe_mode_msb|(1<<22)))  #disable TX
			txant=0   #compose msg with ant id 0 since TX is disabled
		elif ([ $((ant_selected[txant]&BITMASK_ANT_ENABLE_TX)) = 0 ] || [ $rxonly = 1 ]);then
			((dfe_mode_msb=dfe_mode_msb|(1<<22)))  #disable TX
		else
			get_chan_para $txant $core; [ $? -ne 0 ] && channels_start_fail
			((obs_chan_enable=obs_chan_enable|flag_obs))
			if [ $((OBS_DEDICATE_ENABLE & flag_obs)) -ne 0 ];then  #config obs dump addr
				[ $obs_buffer_phy = 0 ] && obs_buffer_phy=$next_FRAMaddr_phy
				set_wordvalue_to_vspa $core $obs_dump_addr $next_FRAMaddr_phy; echo set_wordvalue_to_vspa $core $obs_dump_addr $next_FRAMaddr_phy
				next_FRAMaddr_phy=$((next_FRAMaddr_phy+OBS_SIZE_BUFFER))
				obs_buffer_size=$((obs_buffer_size+OBS_SIZE_BUFFER))
			fi
			option8_tx[$txant]=$option8
			bbsps_tx[txant]=$baseband_txsps
			axiqsps_tx[txant]=$txaxiq
			sym_size_per_ant[txant]=$sym_size
			max_sym_size_per_ant[txant]=$max_sym_size
			upsampling_ratio_per_ant[txant]=$upsampling_ratio
			block_size_per_ant[txant]=$block_size
			if [ $((txant2)) -ne $((0xF)) ];then
			option8_tx[$txant2]=$option8
			bbsps_tx[txant2]=$baseband_txsps
			axiqsps_tx[txant2]=$txaxiq
			fi
			if [ $txant -lt 4 ];then
				txdcs_ls=$txdcs
				scs_ls=$scs
			else
				scs_hs=$scs
				txdcs_hs=$txdcs
			fi	

			invecsize_exp[$txant]=$invecsize
			invecsize_backup=$invecsize
			if [ $((${DCSchan[${ant_map_tx[$txant]}]}&BITMASK_ANT_ENABLE_TX)) -eq 0 ]; then
				((dfe_mode_msb=dfe_mode_msb|(1<<22)))  #disable TX
			else
				#determine input test vector file according to vspa image and config.dat
				tagSPS=""; tagFDD=(_TDD _FDD); tagOPTION8=("" _option8); tagCOMP=("" _compressed)
				[ $baseband_upsampling_rate != 1 ] && { tagSPS=_$baseband_txsps\ksps; tagOPTION8=("" _timedomain); }

				[ $((bandwidth_tx/baseband_upsampling_rate)) -le 100 ] && tagTM=TM3.3 || tagTM=TM3.1
				[ $dpd_model_id = 0 ] || tagTM=TM1.1
				[ $ecpri_comp_decomp_enable = 1 ] && tagTM=TM3.3

				if [ $invecfile_arg = 0 ];then 
					if [ ${default_waveform_filename[tx_fdd]} != 0 ];then
						invecfile=${default_waveform_filename[tx_fdd]}
					else
						invecfile=./test_vectors/$tagTM\_$((bandwidth_tx/baseband_upsampling_rate))\MHz_$scs\kHz${tagFDD[tx_fdd]}${tagOPTION8[option8]}${tagCOMP[ecpri_comp_decomp_enable]}$tagSPS.bin
					fi
				else 
					invecfile=$invecfile_arg
				fi
				
				([ $mimo = 0 ] && [ $((invecsize_backup)) -eq $((invecsize)) ] && [ $invecfile_backup = $invecfile ]) && tv_malloc_cur=$invec_addr_cur_backup
				invec_addr_phy=$tv_malloc_cur
				invec_addr_vir=`phy2vir $tv_malloc_cur`
				addr_tx_wv[$txant]=$tv_malloc_cur
				tv_malloc_cur=`size_align $((tv_malloc_cur+invecsize)) 4096`
				tv_malloc_cur=`printf 0x%x $tv_malloc_cur`
				if [ -f $invecfile ];then
					if [ $((invec_addr_cur_backup)) -ne $((invec_addr_phy)) ];then
					#loading test vector
					clear_mem $invec_addr_vir $invecsize
					filesize=$(stat --format=%s $invecfile)
					numload=$((invecsize/filesize)); remainder=$((invecsize%filesize))
					if [ $filesize -ne $invecsize ];then
						if [ $numload -ge 1 ];then 
							if [ $no_wv_load = 0 ];then
							[ $remainder -ne 0 ] && { echo -e "$print_msg"; echo -e "***ERROR: Input waveform file size $filesize is smaller than expected ${input_waveform_len[$tx_fdd]}ms $invecsize.\n"; channels_start_fail; }
							[ $numload -gt 40 ] && { echo -e "$print_msg"; echo -e "***ERROR: Input waveform file size $filesize is too small than expected ${input_waveform_len[$tx_fdd]}ms $invecsize.\n"; channels_start_fail; }
							str="***WARNING: Input waveform file size $filesize is 1/$numload of expected ${input_waveform_len[$tx_fdd]}ms $invecsize, repeating/concatenating $numload times."
							print_msg="${print_msg}${str}\n"
							warning_list="$warning_list$str\n"
							fi
						else 
							if [ $no_wv_load = 0 ];then
							multiple=$((filesize/invecsize)); remainder=$((filesize%invecsize))
							[ $remainder -ne 0 ] && { echo -e "$print_msg"; echo -e "***ERROR: Input waveform file size $filesize is larger than expected ${input_waveform_len[$tx_fdd]}ms $invecsize.\n"; channels_start_fail; }
							str="***WARNING: Input waveform file size $filesize is $multiple times of expected ${input_waveform_len[$tx_fdd]}ms $invecsize, first $invecsize will be used."
							print_msg="${print_msg}${str}\n"
							warning_list="$warning_list$str\n"
							fi
							numload=1
						fi
					fi
					loadsize=$((invecsize/numload))
					invec_addr_vir1=$invec_addr_vir
					for((i=0;i<numload;i++))
					do
						if [ $no_wv_load = 0 ];then
						[ $fast = 0 ] && print_msg="${print_msg}Loading Input waveform file $invecfile $numload times to address $invec_addr_vir1 with size $invecsize for ant$txant\n"
						loadfile $invec_addr_vir1 $invecfile $loadsize
						echo "./utils/loadmem $invecfile $invec_addr_vir1 $loadsize" >> ./command_init.sh
						fi
						invec_addr_vir1=`printf 0x%x $((invec_addr_vir1+loadsize))`
					done
					if ([ $tx_fdd = 0 ] && [ $fast = 0 ] && [ $wvpd = 1 ]);then
						pattern_detect $invec_addr_vir `size_align $sym_size 32` $sym_size $cpe
						echo detected_pattern="(${detected_pattern[@]})"
						if [ ${#detected_pattern[@]} -ne 0 ];then
						if ([ ${detected_pattern[0]} != ${pattern[0]} ] || [ ${detected_pattern[2]} != ${pattern[2]} ] || [ $((detected_pattern[1] - pattern[1])) -gt 2 ] || [ $((pattern[1] - detected_pattern[1])) -gt 2 ]);then
							str="***WARNING: Detected input waveform pattern (${detected_pattern[@]}) seems different than configured pattern (${pattern[@]})"
							print_msg="${print_msg}${str}\n"
							warning_list="$warning_list$str\n"
						fi
						fi
					fi
					fi
					invecfile_ori[$txant]=$invecfile
					[ $no_wv_load = 0 ] && invecfile_cur[$txant]=$invecfile
				else
					if [ $no_wv_load = 0 ];then
						str="***WARNING: Input waveform file $invecfile does not exist,\n            waveform not loaded. Users can run ./update_test_vector.sh <filename> to load it later."
						print_msg="${print_msg}${str}\n"
						warning_list="$warning_list$str\n"
					fi
				fi
				([ $no_wv_load = 0 ] && [ $test_vector_on_hram = 0 ]) && { pci_bw_req_total=$((pci_bw_req_total+baseband_txsps*32)); pci_bw_req[$txant]=$((baseband_txsps*32)); }
			fi
			invecsize_backup=$invecsize
			invecfile_backup=$invecfile
			invec_addr_cur_backup=$invec_addr_phy
		fi
		
		if [ $((rxant)) -eq $((0xF)) ];then
			((dfe_mode_msb=dfe_mode_msb|(1<<23)))  #disable RX
			rxant=0   #compose msg with ant id 0 since RX is disabled
		elif ([ $((ant_selected[rxant]&BITMASK_ANT_ENABLE_RX)) = 0 ] || [ $txonly = 1 ]);then
			((dfe_mode_msb=dfe_mode_msb|(1<<23)))  #disable RX
		else
			get_chan_para $rxant $core; [ $? -ne 0 ] && channels_start_fail
			option8_rx[$rxant]=$option8rx;
			bbsps_rx[rxant]=$baseband_rxsps
			axiqsps_rx[rxant]=$rxaxiq
			sinad_enable_arr[rxant]=$sinad_enable
			if [ $((rxant2)) -ne $((0xF)) ];then
			option8_rx[$rxant2]=$option8rx;
			bbsps_rx[rxant2]=$baseband_rxsps
			axiqsps_rx[rxant2]=$rxaxiq
			sinad_enable_arr[rxant2]=$sinad_enable
			fi
			if [ $rxant -lt 4 ];then
				rxdcs_ls=$rxdcs
				scs_ls=$scs
			else
				rxdcs_hs=$rxdcs
				scs_hs=$scs
			fi	

			if [ $((${DCSchan[${ant_map_rx[$rxant]}]}&BITMASK_ANT_ENABLE_RX)) -eq 0 ]; then
				((dfe_mode_msb=dfe_mode_msb|(1<<23)))  #disable RX
			fi
		fi
		
		[ $(((dfe_mode_msb&((1<<22)|(1<<23))))) -eq $(((1<<22)|(1<<23))) ] && continue  #both TX and RX disabled
		
		dfe_mode_msb=$(( dfe_mode_msb|no_rx_sym_to_host|(lphy<<9)|(option8<<8)|(dfe_only<<1) )) #set no RX sym and lowPHY only
		((dfe_mode_msb=dfe_mode_msb|0x0E000000|((1-ecpri_comp_decomp_enable)<<7)|(txrestart<<20)|(rxrestart<<21)|(bypass_handshake_rx<<DFE_MODE_RX_HANDSHAKE_BYPASS_IDX)|(bypass_handshake_tx<<DFE_MODE_TX_HANDSHAKE_BYPASS_IDX)))
		((dfe_mode_lsb=dfe_mode_lsb+(iqswap_tx[ant_map_tx[txant]] << 19)+(iqswap_rx[ant_map_rx[rxant]] << 23)))
		[ $((txant2)) -ne $((0xF)) ] && ((dfe_mode_lsb=dfe_mode_lsb+(iqswap_tx[ant_map_tx[txant2]] << 3)))
		[ $((rxant2)) -ne $((0xF)) ] && ((dfe_mode_lsb=dfe_mode_lsb+(iqswap_rx[ant_map_rx[rxant2]] << 7)))
		((dfe_mode_lsb=dfe_mode_lsb+(rx_allowed_ext<<12)))
		
		[ $((ant_map_tx[$txant])) -ge 6 ] && { echo ERROR config in TX ant re-mapping: DCS channel number ${ant_map_tx[$txant]} is illegal; echo; channels_start_fail; }
		[ $((ant_map_rx[$rxant])) -ge 6 ] && { echo ERROR config in RX ant re-mapping: DCS channel number ${ant_map_rx[$rxant]} is illegal; echo; channels_start_fail; }


		if [ $((txant_ori)) -eq $((0xF)) ];then dcs_id_tx=7
		elif ([ $((ant_selected[txant_ori]&BITMASK_ANT_ENABLE_TX)) = 0 ] || [ $rxonly = 1 ]);then dcs_id_tx=$((ant_map_tx[$txant_ori])) #dcs_id_tx=7
		elif [ $((${DCSchan[${ant_map_tx[$txant_ori]}]}&BITMASK_ANT_ENABLE_TX)) -eq 0 ];then dcs_id_tx=$((ant_map_tx[$txant_ori])) #dcs_id_tx=7
		else 
			dcs_id_tx=$((ant_map_tx[$txant_ori]))
			if [ $txant_ori -lt 4 ];then ((num_T_LS_enabled++)) 
			else ((num_T_HS_enabled++)) 
			fi
			dcs_enable[dcs_id_tx]=$((dcs_enable[dcs_id_tx]+BITMASK_ANT_ENABLE_TX))
			ant_enable[txant_ori]=$((ant_enable[txant_ori]+BITMASK_ANT_ENABLE_TX))
		fi
		
		if [ $((rxant_ori)) -eq $((0xF)) ];then dcs_id_rx=7
		elif ([ $((ant_selected[rxant_ori]&BITMASK_ANT_ENABLE_RX)) = 0 ] || [ $txonly = 1 ]);then dcs_id_rx=$((ant_map_rx[$rxant_ori])) #dcs_id_rx=7
		elif [ $((${DCSchan[${ant_map_rx[$rxant_ori]}]}&BITMASK_ANT_ENABLE_RX)) -eq 0 ];then dcs_id_rx=$((ant_map_rx[$rxant_ori])) #dcs_id_rx=7
		else 
			dcs_id_rx=$((ant_map_rx[$rxant_ori]))
			if [ $rxant_ori -lt 4 ];then ((num_R_LS_enabled++)) 
			else ((num_R_HS_enabled++))
			fi
			dcs_enable[dcs_id_rx]=$((dcs_enable[dcs_id_rx]+BITMASK_ANT_ENABLE_RX))
			ant_enable[rxant_ori]=$((ant_enable[rxant_ori]+BITMASK_ANT_ENABLE_RX))
		fi
		
		if [ $((txant2)) -eq $((0xF)) ];then dcs_id_tx2=7
		elif ([ $((ant_selected[txant2]&BITMASK_ANT_ENABLE_TX)) = 0 ] || [ $rxonly = 1 ]);then dcs_id_tx2=7
		elif [ $((${DCSchan[${ant_map_tx[$txant2]}]}&BITMASK_ANT_ENABLE_TX)) -eq 0 ];then dcs_id_tx2=7
		else 
			dcs_id_tx2=$((ant_map_tx[$txant2]))
			if [ $txant2 -lt 4 ];then ((num_T_LS_enabled++)) 
			else ((num_T_HS_enabled++)) 
			fi
			dcs_enable[dcs_id_tx2]=$((dcs_enable[dcs_id_tx2]+BITMASK_ANT_ENABLE_TX))
			ant_enable[txant2]=$((ant_enable[txant2]+BITMASK_ANT_ENABLE_TX))
		fi
		
		if [ $((rxant2)) -eq $((0xF)) ];then dcs_id_rx2=7
		elif ([ $((ant_selected[rxant2]&BITMASK_ANT_ENABLE_RX)) = 0 ] || [ $txonly = 1 ]);then dcs_id_rx2=7
		elif [ $((${DCSchan[${ant_map_rx[$rxant2]}]}&BITMASK_ANT_ENABLE_RX)) -eq 0 ];then dcs_id_rx2=7
		else 
			dcs_id_rx2=$((ant_map_rx[$rxant2]))
			if [ $rxant2 -lt 4 ];then ((num_R_LS_enabled++)) 
			else ((num_R_HS_enabled++))
			fi
			dcs_enable[dcs_id_rx2]=$((dcs_enable[dcs_id_rx2]+BITMASK_ANT_ENABLE_RX))
			ant_enable[rxant2]=$((ant_enable[rxant2]+BITMASK_ANT_ENABLE_RX))
		fi
		
		((dfe_mode_lsb=dfe_mode_lsb|(dcs_id_tx << 16)|(dcs_id_tx2 << 0)))
		((dfe_mode_lsb=dfe_mode_lsb|(dcs_id_rx << 20)|(dcs_id_rx2 << 4)))
		dfe_mode_msb=$((dfe_mode_msb | (hwdcm<<6) | (bwdiv<<4) | (hsdiv2<<3) | (lsdiv2<<2) ))
		dfe_mode_msb=`HEX $dfe_mode_msb`; dfe_mode_lsb=`HEX $dfe_mode_lsb`
		
		sym_buf_size=`size_align $((sym_size*4)) 128`
		sym_buf_config_msb=`printf "0x%08X" $(( 0x10000000 + ((num_sym_in_queue_rx/2)<<20) + (rx_sym_queue_base>>12) ))`
		sym_buf_config_lsb=`printf "0x%08X" $(( (((sym_buf_size/128)&0xFF)<<24) + ((num_sym_in_queue_tx/2)<<20) + (tx_sym_queue_base>>12) ))`
		txcore=$core #${anttx[$ant]}
		rxcore=$core #${antrx[$ant]}
		one_enabled_dfe_core=$core
		tid=${tidant[$txant]}
		rid=${ridant[$rxant]}
		inject_msb=`size_align $((sym_size*4)) 128`
		inject_msb=`printf "0x%08x" $((0x0A110000 + (inject_msb/128) + (tid<<15)))`
		inject_lsb=`printf "0x%08x" $(((sym_num<<20)+(${addr_tx_wv[$txant]}>>12)))`
		
		if ([ $extlog = 1 ] && [ $txant = 0 ]);then    #setup external log buffer for ant0 only.
		set_wordvalue_to_vspa $core $ext_log_buf_base $((trace_log_buf_base+core*trace_log_buf_size_per_core))
		set_wordvalue_to_vspa $core $ext_log_buf_size $((trace_log_buf_size_per_core))
		score=$((slave_core[core]))
		if [ $score != $core ];then
		set_wordvalue_to_vspa $score $ext_log_buf_base $((trace_log_buf_base+score*trace_log_buf_size_per_core))
		set_wordvalue_to_vspa $score $ext_log_buf_size $((trace_log_buf_size_per_core))
		fi
		fi
		
		
		if ([ $tx_fdd = 0 ] && [ $dcsfdd = 1 ] && [ $vspa_dev_type = LA9310 ]);then
			if [ $((${#pattern[@]} % 6)) -eq 0 ];then
			num_sym_in_slot=14
			for ((i=0;i<${#pattern[@]};i=i+6))
			do
				skip0=0
				dlsym=$((  pattern[0+i]*num_sym_in_slot+pattern[1+i]  ))
				skip1=$(( (pattern[2+i]*num_sym_in_slot+pattern[3+i]) + ((num_sym_in_slot-pattern[1+i]-pattern[3+i])%num_sym_in_slot) + (num_sym_in_slot*pattern[4+i]) + (num_sym_in_slot*pattern[5+i]) ))
				pattern_size_dl=$(( (skip1<<16) + (dlsym<<8) + skip0 ))
				
				skip0=$(( (pattern[0+i]*num_sym_in_slot+pattern[1+i]) + ((num_sym_in_slot-pattern[1+i]-pattern[3+i])%num_sym_in_slot) + (num_sym_in_slot*pattern[4+i]) ))
				ulsym=$((  pattern[2+i]*num_sym_in_slot+pattern[3+i]  ))
				skip1=$((  num_sym_in_slot*pattern[5+i] ))
				pattern_size_ul=$(( (skip1<<16) + (ulsym<<8) + skip0 ))
				
				[ $cpe = 0 ] && { pattern_size_tx=$pattern_size_dl; pattern_size_rx=$pattern_size_ul; } || { pattern_size_rx=$pattern_size_dl; pattern_size_tx=$pattern_size_ul; }
				
				set_wordvalue_to_vspa $txcore $((tx_pattern_entry+i/6*4)) $pattern_size_tx
				set_wordvalue_to_vspa $txcore $((rx_pattern_entry+i/6*4)) $pattern_size_rx
			done
			set_wordvalue_to_vspa $txcore $num_patterns $((i/6)) #set num of entries
			
			elif [ $((${#pattern[@]} % 4)) -eq 0 ];then
			for ((i=0;i<${#pattern[@]};i=i+4))
			do
				skip0=0
				dlsym=$((  pattern[0+i]  ))
				skip1=$((  pattern[1+i] + pattern[2+i] +  pattern[3+i] ))
				pattern_size_dl=$(( (skip1<<16) + (dlsym<<8) + skip0 ))
				
				skip0=$((  pattern[0+i] + pattern[1+i] ))
				ulsym=$((  pattern[2+i]  ))
				skip1=$((  pattern[3+i]  ))
				pattern_size_ul=$(( (skip1<<16) + (ulsym<<8) + skip0 ))
				
				[ $cpe = 0 ] && { pattern_size_tx=$pattern_size_dl; pattern_size_rx=$pattern_size_ul; } || { pattern_size_rx=$pattern_size_dl; pattern_size_tx=$pattern_size_ul; }
				
				set_wordvalue_to_vspa $txcore $((tx_pattern_entry+i/4*4)) $pattern_size_tx
				set_wordvalue_to_vspa $txcore $((rx_pattern_entry+i/4*4)) $pattern_size_rx
			done
			set_wordvalue_to_vspa $txcore $num_patterns $((i/4)) #set num of entries
			fi
		fi
		

		
		#send 1st init msg: SYMBOL BUFFER STRUCT
		echo "./utils/vspa_mbox send $txcore $host_vspa_mbox_id $sym_buf_config_msb $sym_buf_config_lsb; ./utils/vspa_mbox recv $txcore $host_vspa_mbox_id" >> ./command_init.sh
		vspa_mbox_ifsend $txcore $host_vspa_mbox_id $sym_buf_config_msb $sym_buf_config_lsb; [ $msg_recv_flag = 0 ] && vspa_mbox_ifrecv $txcore $host_vspa_mbox_id
		./utils/memrw w 32 $((test_tool_env_buf_struct_msg+txcore*8+0)) $sym_buf_config_msb $((test_tool_env_buf_struct_msg+txcore*8+4)) $sym_buf_config_lsb
		print_msg="${print_msg}Sending SYMBOL BUFFER STRUCT message to core $txcore: vspa_mbox send $txcore $host_vspa_mbox_id $sym_buf_config_msb $sym_buf_config_lsb, "
		([ $msg_recv_flag = 0 ] || [ $((msg_recv_msb32&0xFF000000)) -ne $((0x11000000)) ]) && { echo -e "$print_msg"; echo "***ERROR: VSPA core $txcore did not respond to Buffer struct config msg."; channels_start_fail; }
		print_msg="${print_msg}ACK MSB:$msg_recv_msb32 LSB:$msg_recv_lsb32\n"
		
		if [ $dfe_only = 0 ];then
		if ([ $((idle)) = 1 ] || [ $((dfe_mode_msb&(1<<22))) -ne 0 ]); then  #set single tone mode with amp=0 for idle or channel not enabled
			print_msg="${print_msg}Setting TX channel to idle state to core $txcore    : vspa_mbox send $txcore $host_vspa_mbox_id 0x0a0e0000 0x40000000\n"
			echo ./utils/vspa_mbox send $txcore $host_vspa_mbox_id 0x0a0e0000 0x40000000 >> ./command_init.sh
			vspa_mbox_ifsend $txcore $host_vspa_mbox_id 0x0a0e0000 0x40000000
		fi
		if ([ $((type_ru | force_ru)) -eq $((1)) ] && [ $cell_state != $CELL_STATE_SEARCH ] && [ $sinad = 0 ] && [ $((dfe_mode_msb&(1<<22))) -eq 0 ] && [ $rt = 0 ]); then
			print_msg="${print_msg}Sending INJECT DL TEST VECTOR msg to core $txcore   : vspa_mbox send $txcore $host_vspa_mbox_id $inject_msb $inject_lsb\n"
			echo ./utils/vspa_mbox send $txcore $host_vspa_mbox_id $inject_msb $inject_lsb >> ./command_init.sh
			inject_freq_domain_tx $txcore $host_vspa_mbox_id $inject_msb $inject_lsb
		fi
		fi
		
		if ([ $size_inject_rx -ne 0 ] && [ $((dfe_mode_msb&(1<<23))) -eq 0 ]);then
			score=$((slave_core[core]))
			block_size_axiq=$((block_size*downsampling_ratio))
			size_inject_rx=$((size_inject_rx/block_size_axiq*block_size_axiq)) #align inject size to block size.
			set_wordvalue_to_vspa $score $rx_inject_addr $addr_inject_rx
			set_wordvalue_to_vspa $score $rx_inject_size $size_inject_rx
			echo RX time domain inject configured for ant $rxant from address `HEX $addr_inject_rx` size $size_inject_rx
		fi
		
		#send 2nd init msg: DFE MODE
		echo "./utils/vspa_mbox send $txcore $host_vspa_mbox_id $dfe_mode_msb $dfe_mode_lsb; ./utils/vspa_mbox recv $txcore $host_vspa_mbox_id" >> ./command_init.sh
		vspa_mbox_ifsend $txcore $host_vspa_mbox_id $dfe_mode_msb $dfe_mode_lsb; [ $msg_recv_flag = 0 ] && vspa_mbox_ifrecv $txcore $host_vspa_mbox_id
		./utils/memrw w 32 $((test_tool_env_dfe_mode_msg+txcore*8+0)) $dfe_mode_msb $((test_tool_env_dfe_mode_msg+txcore*8+4)) $dfe_mode_lsb
		([ $msg_recv_flag = 0 ] || [ $((msg_recv_msb32&0xFF000000)) -ne $((0x0F000000)) ]) && { echo -e "$print_msg"; echo "***ERROR: VSPA core $txcore did not respond to DFE mode msg."; channels_start_fail; }
		print_msg="${print_msg}Sending DFE MODE CONFIG message to core $txcore     : vspa_mbox send $txcore $host_vspa_mbox_id `HEX $dfe_mode_msb` `HEX $dfe_mode_lsb`, ACK MSB:$msg_recv_msb32 LSB:$msg_recv_lsb32\n"

		#send 3rd init msg: STATIC SLOT FORMAT if needed
		if [ $vspa_dev_type = LA12xx ];then
		if [ $((tx_fdd&rx_fdd)) = 0 ];then
		echo "./utils/vspa_mbox send $txcore $host_vspa_mbox_id $pattern_msg1 $pattern_msg0; ./utils/vspa_mbox recv $txcore $host_vspa_mbox_id" >> ./command_init.sh
		vspa_mbox_ifsend $txcore $host_vspa_mbox_id $pattern_msg1 $pattern_msg0; [ $msg_recv_flag = 0 ] && vspa_mbox_ifrecv $txcore $host_vspa_mbox_id
		print_msg="${print_msg}Sending SLOT PATTERN CONFIG message to core $txcore : vspa_mbox send $txcore $host_vspa_mbox_id $pattern_msg1 $pattern_msg0, "
		([ $msg_recv_flag = 0 ] || [ $((msg_recv_msb32&0xFF000000)) -ne $((0x13000000)) ]) && { echo -e "$print_msg"; echo "***ERROR: VSPA core $txcore did not respond to Slot pattern config msg."; channels_start_fail; }
		print_msg="${print_msg}ACK MSB:$msg_recv_msb32 LSB:$msg_recv_lsb32\n"
		fi
		fi

		
		#check vspa initialized status
		swversion=`./utils/memrw r 32 $((modembase_phy+0x1000000+core*0x4000+4))`
		((flag_dfe_initialized=(swversion>>12)&1))
		if [ $flag_dfe_initialized = 0 ];then
			echo -e "$print_msg"
			echo -e "***ERROR: VSPA initialization failed on core $core, SWVERSION_REG=$swversion\n"; exit 1
			channels_start_fail
		fi
	done

	[ $fast = 0 ] && echo -e "$print_msg"
	[ $((num_T_LS_enabled+num_T_HS_enabled+num_R_LS_enabled+num_R_HS_enabled)) -eq 0 ] && { echo -e "\n***ERROR: No channel is started, the ant_id you specified does not exist.\n"; channels_start_fail; }
	if ([ $num_T_LS_enabled -gt 2 ] && [ $num_R_LS_enabled -gt 2 ] && [ $((tx_fdd|dcsfdd)) = 1 ] && [ $bandwidth -eq 100 ] && [ $((lphy+dfe_only)) -eq 0 ]);then
		str="***WARNING: For 100Mhz, 2T2R/4T/4R FDD or 4T4R TDD are supported with full functinalities. \nYou are running more than 2T2R FDD, the system is set with reduced functionalities in RX.\nDisabled: RX Down sampling filter, RX low pass filter, RX FFT\nEnabled: RX QEC, RX time domain Dumping"
		warning_list="$warning_list$str\n"
		for((i=0;i<NUM_CORES;i++))
		do
		[ $((dfe_core[i])) = 0 ] && continue
		kernel_disable $i $KERNELS_DISABLE_BITMASK_RX_FFT $KERNELS_DISABLE_BITMASK_RX_FFT
		kernel_disable $i $KERNELS_DISABLE_BITMASK_RX_LPF $KERNELS_DISABLE_BITMASK_RX_LPF
		kernel_disable $i $KERNELS_DISABLE_BITMASK_DOWNSAMPLING $KERNELS_DISABLE_BITMASK_DOWNSAMPLING
		done
	fi
	
	if [ $test_vector_on_hram = 1 ];then
		if [ $((tv_malloc_cur)) -ge $((HRAMaddr_phy+HRAM_size)) ];then
			echo ***ERROR: Input test vector exceeds HRAM size; channels_start_fail
		fi
		next_HRAMaddr_phy=$tv_malloc_cur
	else
		ddr_malloc_cur=$tv_malloc_cur
	fi
	size_tx_test_vector=$((tv_malloc_cur-addr_tx_test_vector))
	addr_dump=$ddr_malloc_cur; addr_dump_vir=`phy2vir $addr_dump`
	ddr_malloc_cur=`printf 0x%x $((ddr_malloc_cur + size_dump))` 
	end_ddr=$ddr_malloc_cur
	addr_inject_tx=$addr_dump; size_inject_tx=0;
	
	if [ $((end_ddr)) -gt $((ddr_phy+ddr_size)) ];then
		str="***WARNING: DDR size larger than available. Size needed `printf "0x%x" $((end_ddr-ddr_phy))`, size available `printf "0x%x" $ddr_size`"
		echo $str; warning_list="$warning_list$str\n"
	fi
	
	
	echo "loopback=$loopback; rloopback_time=$rloopback_time; rloopback_freq=$rloopback_freq; num_errors=0; first_error=0" > runtime_config.txt
	echo "ant_remap=$ant_remap; ant_map_tx=(${ant_map_tx[@]}); ant_map_rx=(${ant_map_rx[@]})" >> ./runtime_config.txt
	echo -e "DCSchan=(${DCSchan[@]})\ndfe_core=(${dfe_core[@]}); slave_core=(${slave_core[@]}); one_dfe_core=$one_dfe_core\ntest_tool_name=$test_tool_name; test_tool_version=$test_tool_version; vspa_image_version=$vspa_image_version; revision=$revision; ver_min=$ver_min; ver_maj=$ver_maj\niqswap_tx=(${iqswap_tx[@]}); iqswap_rx=(${iqswap_rx[@]}); MAX_NUM_1R_IN_CORE=$MAX_NUM_1R_IN_CORE" >> ./runtime_config.txt
	echo -e "anttx=(${anttx[@]}); antrx=(${antrx[@]}); coretx_tr0=(${coretx_tr0[@]}); corerx_tr0=(${corerx_tr0[@]})\ncoretx_tr1=(${coretx_tr1[@]}); corerx_tr1=(${corerx_tr1[@]});" >> ./runtime_config.txt
	echo -e "fr1_used=$fr1_used; fr2_used=$fr2_used\nnum_T_LS=$num_T_LS; num_T_HS=$num_T_HS; num_R_LS=$num_R_LS; num_R_HS=$num_R_HS\ntidcore=(${tidcore[@]}); ridcore=(${ridcore[@]}); tidant=(${tidant[@]}); ridant=(${ridant[@]}); idle=$idle; sinad=$sinad " >> ./runtime_config.txt
	echo -e "arg_nhwdcm=$arg_nhwdcm; lphy=$lphy; dfe_only=$dfe_only; tx_fdd=$tx_fdd; rx_fdd=$rx_fdd; use_nxp_l1c=$use_nxp_l1c; mimo=$mimo; cpe=$cpe; option8=$option8_cfg; option8_cfg=$option8_cfg; ecpri_comp_decomp_enable=$ecpri_comp_decomp_enable; fast=$fast\ninput_waveform_len=(${input_waveform_len[@]}); nrb=$nrb; prach_wv=0; use_specified_pattern=$use_specified_pattern; specified_pattern=(${specified_pattern[@]}) " >> ./runtime_config.txt
	echo "cfo_disable=$cfo_disable; txqec_timing_skew=$txqec_timing_skew; rxqec_timing_skew=$rxqec_timing_skew; pattern=(${pattern[@]}); dpd_model_id=$dpd_model_id; flag_deqec=$flag_deqec; dpd_model_id_para_pre=(${dpd_model_id_para[@]})" >> ./runtime_config.txt
	echo "trace_log_buf_base=$trace_log_buf_base; trace_log_buf_size_per_core=$trace_log_buf_size_per_core; trace_log_buf_size=$trace_log_buf_size; test_tool_env_base_phy=$test_tool_env_base_phy; test_tool_env_size=$test_tool_env_size; tx_sym_queue_base=$tx_sym_queue_base; tx_sym_queue_size=$tx_sym_queue_size; rx_sym_queue_base=$rx_sym_queue_base; rx_sym_queue_size=$rx_sym_queue_size" >> ./runtime_config.txt
	echo "celltrack_extbuf_base=$celltrack_extbuf_base; celltrack_extbuf_size=$celltrack_extbuf_size; obs_buffer_phy=$obs_buffer_phy; obs_buffer_size=$obs_buffer_size" >> ./runtime_config.txt
	echo -e "dcsfdd=$dcsfdd; hwdcm=$hwdcm; lsdiv2=$lsdiv2; hsdiv2=$hsdiv2; bwdiv=$bwdiv; pci_bw_req_total=$pci_bw_req_total; pci_bw_req=(${pci_bw_req[@]})\nnum_T_LS_enabled=$num_T_LS_enabled; num_R_LS_enabled=$num_R_LS_enabled; num_T_HS_enabled=$num_T_HS_enabled; num_R_HS_enabled=$num_R_HS_enabled" >> ./runtime_config.txt
	echo -e "one_enabled_dfe_core=$one_enabled_dfe_core; option8_tx=(${option8_tx[@]}); option8_rx=(${option8_rx[@]})\nsym_size_per_ant=(${sym_size_per_ant[@]}); max_sym_size_per_ant=(${max_sym_size_per_ant[@]}); upsampling_ratio_per_ant=(${upsampling_ratio_per_ant[@]}); bbsps_tx=(${bbsps_tx[@]}); bbsps_rx=(${bbsps_rx[@]}); axiqsps_tx=(${axiqsps_tx[@]}); axiqsps_rx=(${axiqsps_rx[@]}); sinad_enable_arr=(${sinad_enable_arr[@]})" >> ./runtime_config.txt
	echo -e "invecfile_ori=(${invecfile_ori[@]}); invecfile_cur=(${invecfile_cur[@]}); invecsize_exp=(${invecsize_exp[@]})\ndcs_enable=(${dcs_enable[@]}); ant_enable=(${ant_enable[@]}); block_size_per_ant=(${block_size_per_ant[@]})" >> ./runtime_config.txt
	echo -e "test_vector_on_hram=$test_vector_on_hram; next_HRAMaddr_phy=$next_HRAMaddr_phy\naddr_tx_test_vector=$addr_tx_test_vector; size_tx_test_vector=$size_tx_test_vector; addr_tx_wv=(${addr_tx_wv[@]})\naddr_inject_rx=$addr_inject_rx; addr_inject_tx=$addr_inject_tx; size_inject_tx=$size_inject_tx; size_inject_rx=$size_inject_rx; addr_dump=$addr_dump; addr_dump_vir=$addr_dump_vir; size_dump=$size_dump; end_ddr=$end_ddr " >> ./runtime_config.txt

	./utils/memrw w 32 $test_tool_env_boot_vspa_ind 0 #channels already started here, clear the vspa boot flag.
	
	for((ant=0;ant<NUM_ANTS;ant++))
	do
		if [ $((ant_enable[ant]&BITMASK_ANT_ENABLE_TX)) -ne 0 ];then
			[ $((sym_size_per_ant[ant])) -le $((max_sym_size_per_ant[ant]/2)) ] && [ $((upsampling_ratio_per_ant[ant])) -eq 4 ] && ./update_filter_coeff.sh 4xup ./test_vectors/h_4x_64tap_gain4p8_BW8x.bin
			[ $((pnswap_tx_I[ant_map_tx[ant]] | pnswap_tx_Q[ant_map_tx[ant]])) = 1 ] && ./update_qec_coeff_tx.sh $ant dis
			tx_scaling_output=`./utils/memrw r 32 $((test_tool_env_tx_scaling_output+ant*4))`
			[ $((tx_scaling_output)) -ne 100 ] && log=`./scale_percent.sh $ant 100` #restore scaling to 100% in case that scaling is done in previous run
			tx_scaling_input=`./utils/memrw r 32 $((test_tool_env_tx_scaling_input+ant*4))`
			[ $((tx_scaling_input)) -ne 100 ] && log=`./update_phase_compensation_coeff.sh $ant scale=100`
		fi
		if [ $((ant_enable[ant]&BITMASK_ANT_ENABLE_RX)) -ne 0 ];then
			[ $((pnswap_rx_I[ant_map_rx[ant]] | pnswap_rx_Q[ant_map_rx[ant]])) = 1 ] && ./update_qec_coeff_rx.sh $ant dis
			rx_scaling=`./utils/memrw r 32 $((test_tool_env_rx_scaling+ant*4))`
			[ $((rx_scaling)) -ne 100 ] && log=`./scale_percent.sh rx $ant 100`
		fi
		if [ $((ant_enable[ant]&BITMASK_ANT_ENABLE_TRX)) -eq $((BITMASK_ANT_ENABLE_TRX)) ];then
			txcore=${anttx[$ant]}; txscore=${slave_core[txcore]}
			rxcore=${antrx[$ant]}; rxscore=${slave_core[rxcore]}
			if [ $rloopback_freq = 1 ];then
				set_wordvalue_to_vspa $rxcore $rx_sym_buf_base_dump `get_wordvalue_from_vspa $txcore $tx_sym_buf_base_inject`
				set_wordvalue_to_vspa $rxcore $rx_num_sym_in_buff_dump `get_wordvalue_from_vspa $txcore $tx_num_sym_in_buf_inject`
				echo Reverse loopback freq domain, loopback delay is ${input_waveform_len[tx_fdd]} ms.
			fi
			if [ $rloopback_time = 1 ];then
				if [ ${axiqsps_tx[ant]} -ne ${axiqsps_rx[ant]} ];then
					echo -e "***ERROR: TX DAC and RX ADC sampling rate is different, failed to configure reverse loopback time domain."
					[ ${axiqsps_tx[ant]} -eq $((axiqsps_rx[ant]*2)) ] && echo -e "Try ./boot_vspa.sh lsdiv2 to set same TX/RX sampling rate."
					channels_start_fail
				fi
				./inject_time_domain_tx.sh $ant 
				set_wordvalue_to_vspa $rxscore $rx_timedomain_dump_addr `get_wordvalue_from_vspa $txscore $tx_timedomain_inject_addr`
				set_wordvalue_to_vspa $rxscore $rx_timedomain_dump_size `get_wordvalue_from_vspa $txscore $tx_timedomain_inject_size`
			fi
		fi
	done
	
	if [ $type_ru -eq 0 ]; then #ISC need start PHY TX/RX core. PHY TX/RX core ID predefined as 2, 0 for FR2
		if [ $fr1_used = 1 ];then
		txcore=6
		rxcore=4
		dump_msb=`printf "0x%08x" $((0x0A1c4067))`
		dump_lsb=0x01c`printf "%x" $((ddr_phy>>12))`
		else
		txcore=2
		rxcore=0
		dump_msb=`printf "0x%08x" $((0x0A1c4063))`
		dump_lsb=0x01c`printf "%x" $((ddr_phy>>12))`
		fi
		echo "hiphy_txcore=$txcore; hiphy_rxcore=$rxcore" >> ./runtime_config.txt
		
		((dfe_mode_msb=0x0E00001C|(tx_fdd<<12)|(rx_fdd<<13)))
		dfe_mode_lsb=0
		dfe_mode_msb=`printf "0x%08x" $dfe_mode_msb`
		inject_lsb=`printf "0x%08x" $(((sym_num<<20)+(addr_tx_test_vector>>12)))`
		
		echo
		echo Config PHY TX RX cores:

		echo -n "Sending DFE MODE CONFIG msg to PHY TX core $txcore  : "
		echo "vspa_mbox send $txcore $host_vspa_mbox_id $dfe_mode_msb $dfe_mode_lsb "
		vspa_mbox_ifsend $txcore $host_vspa_mbox_id $dfe_mode_msb $dfe_mode_lsb; [ $msg_recv_flag = 0 ] && vspa_mbox_ifrecv $txcore $host_vspa_mbox_id
		
		echo -n "Sending SLOT PATTERN CONFIG message to core $txcore : "
		echo "vspa_mbox send $txcore $host_vspa_mbox_id $pattern_msg1 $pattern_msg0"
		vspa_mbox_ifsend $txcore $host_vspa_mbox_id $pattern_msg1 $pattern_msg0; [ $msg_recv_flag = 0 ] && vspa_mbox_ifrecv $txcore $host_vspa_mbox_id
			
		echo -n "Sending INJECT DL TEST VECTOR msg to core $txcore   : "
		echo vspa_mbox send $txcore $host_vspa_mbox_id $inject_msb $inject_lsb
		vspa_mbox_ifsend $txcore $host_vspa_mbox_id $inject_msb $inject_lsb

		
		echo -n "Sending SYM BUFF STRUCT msg to PHY RX core $rxcore  : "
		echo "vspa_mbox send $rxcore $host_vspa_mbox_id $sym_buf_config_msb $sym_buf_config_lsb "
		vspa_mbox_ifsend $rxcore $host_vspa_mbox_id $sym_buf_config_msb $sym_buf_config_lsb; [ $msg_recv_flag = 0 ] && vspa_mbox_ifrecv $txcore $host_vspa_mbox_id

		echo -n "Sending DFE MODE CONFIG msg to PHY RX core $rxcore  : "
		echo "vspa_mbox send $rxcore $host_vspa_mbox_id $dfe_mode_msb $dfe_mode_lsb "
		vspa_mbox_ifsend $rxcore $host_vspa_mbox_id $dfe_mode_msb $dfe_mode_lsb; [ $msg_recv_flag = 0 ] && vspa_mbox_ifrecv $rxcore $host_vspa_mbox_id
		
		echo -n "Sending SLOT PATTERN CONFIG msg to PHY RX $rxcore   : "
		echo vspa_mbox send $rxcore $host_vspa_mbox_id $pattern_msg1 $pattern_msg0
		vspa_mbox_ifsend $rxcore $host_vspa_mbox_id $pattern_msg1 $pattern_msg0; [ $msg_recv_flag = 0 ] && vspa_mbox_ifrecv $rxcore $host_vspa_mbox_id
		
		echo -n "Sending DUMP UL SYMBOLS msg to PHY RX core $rxcore  : "
		echo vspa_mbox send $rxcore $host_vspa_mbox_id $dump_msb $dump_lsb
		vspa_mbox_ifsend $rxcore $host_vspa_mbox_id $dump_msb $dump_lsb
	fi

	
	#form l1c mailbox msg
	if [ $vspa_dev_type = LA12xx ];then
	tx_dcs_bitmask=0; rx_dcs_bit_mask=0
	for((i=0;i<NUM_ANTS;i++))
	do
		[ $((dcs_enable[i]&BITMASK_ANT_ENABLE_TX)) -ne 0 ] && tx_dcs_bitmask=$(( tx_dcs_bitmask | (1<<(i)) ))
		[ $((dcs_enable[i]&BITMASK_ANT_ENABLE_RX)) -ne 0 ] && rx_dcs_bitmask=$(( rx_dcs_bitmask | (1<<(i)) ))
	done

	[ $scs_ls -ne 0 ] && l1c_scs=$scs_ls || l1c_scs=$scs_hs
	if [ $l1c_scs = 15 ];then		l1c_scs=0
	elif [ $l1c_scs = 60 ];then		l1c_scs=2
	elif [ $l1c_scs = 120 ];then	l1c_scs=3
	elif [ $l1c_scs = 240 ];then	l1c_scs=4
	elif [ $l1c_scs = 480 ];then	l1c_scs=5
	else							l1c_scs=1
	fi
	
	tx_dcs_bitmask=$((tx_dcs_bitmask|(tx_fdd<<6)|(lphy<<31)|(l1c_scs<<28)))
	rx_dcs_bitmask=$((rx_dcs_bitmask|(rx_fdd<<6)|(0x80<<24)))
	echo L1C CONFIG DCS PARA mailbox msg sent by VSPA core $one_dfe_core mailbox $((1-host_vspa_mbox_id )) MSB `HEX $rx_dcs_bitmask` LSB `HEX $tx_dcs_bitmask`
	vspa_mbox_ifsend $one_dfe_core $host_vspa_mbox_id $rx_dcs_bitmask $tx_dcs_bitmask
	echo "./utils/vspa_mbox send $one_dfe_core $host_vspa_mbox_id $rx_dcs_bitmask $tx_dcs_bitmask" >> ./command_init.sh

	sleep 1
	vspa_mbox_ifrecv $one_dfe_core $host_vspa_mbox_id
	echo "./utils/vspa_mbox recv $one_dfe_core $host_vspa_mbox_id" >> ./command_init.sh
	if ([ $msg_recv_flag = 0 ] || [ $((msg_recv_msb32 & 0xFE000000)) -ne $((0x80000000)) ]);then
		echo e200 does not support L1C CONFIG by mailbox, will use legacy l1c interface.
	else
		echo e200 supports L1C CONFIG by mailbox, e200 version `HEX $((msg_recv_msb32 & 0xFFF))`
		use_nxp_l1c=2
	fi
	fi
	
	
#enable DCS
if [ $use_nxp_l1c = 1 ];then
if [ $vspa_dev_type = LA9310 ];then
	rx_ant=0
	for ((i=0;i<NUM_ANTS;i++))
	do
		if [ $((dcs_enable[i]&BITMASK_ANT_ENABLE_RX)) -ne 0 ];then
		rx_ant=$(( rx_ant | (1<<i) ))
		fi
	done
	dpdk-dfe_app -c "config rx ant $rx_ant"
	echo dpdk-dfe_app -c "config rx ant $rx_ant"
	echo dpdk-dfe_app -c \"config rx ant $rx_ant\" >> ./command_init.sh
	
	if [ $((tx_fdd|rx_fdd|dcsfdd)) -ne 0 ];then  #FDD
		echo dpdk-dfe_app -c "fdd start"
		dpdk-dfe_app -c "fdd start"
		echo dpdk-dfe_app -c \"fdd start\" >> ./command_init.sh
	else
		pattern_digits=${pattern[0]}
		for ((i=1;i<${#pattern[@]};i++))
		do
				pattern_digits="$pattern_digits,${pattern[i]}"
		done

		echo dpdk-dfe_app -c "config scs $scs"
		dpdk-dfe_app -c "config scs $scs"
		echo dpdk-dfe_app -c \"config scs $scs\" >> ./command_init.sh
		echo dpdk-dfe_app -c "tdd config pattern_fr1fr2 $pattern_digits"
		dpdk-dfe_app -c "tdd config pattern_fr1fr2 $pattern_digits"
		echo dpdk-dfe_app -c \"tdd config pattern_fr1fr2 $pattern_digits\" >> ./command_init.sh
		
		echo dpdk-dfe_app -c "tdd start"
		dpdk-dfe_app -c "tdd start"
		echo dpdk-dfe_app -c \"tdd start\" >> ./command_init.sh
	fi
	sleep 1  #wait for M4 to drive DCS
else #LA12xx

	OBS_DEDICATE_ENABLE=$((OBS_DEDICATE_ENABLE & obs_chan_enable))
	if [ $OBS_DEDICATE_ENABLE -ne 0 ];then
		[ $obs_sps = 0 ] && { OBS_DEDICATE_ENABLE=0; echo HSDCS OBS channels can not be enabled as they are not enabled during boot stage.; }
		([ $OBS_DEDICATE_ENABLE = 1 ] && [ $((OBS_DAC_SPS/1000000)) -ne $obs_sps ]) && { echo ***ERROR: HSDCS OBS sampling rate set during boot stage did not match the setting in config.dat; channels_start_fail; }
	fi

	measure_tbgen_clock_end $one_dfe_core      #this function will measure and get values for tbgen1_freq and tbgen2_freq
	echo Measured TBGEN1 TBGEN2 frequencies: $tbgen1_freq $tbgen2_freq
	
	if ([ $tbgen1_freq -eq 0 ] && [ $fr1_used = 1 ]);then
		echo ***ERROR: You are using FR1 but TBGEN1 is de-featured in current device, please choose vspa images that does not use LSDCS.
		channels_start_fail
	fi
	if ([ $tbgen2_freq -eq 0 ] && [ $fr2_used = 1 ]);then
		echo ***ERROR: You are using FR2 but TBGEN2 is de-featured in current device, please choose vspa images that does not use HSDCS.
		channels_start_fail
	fi
	
	#TBGEN Sampling Frequency
	((lsdac_sps=txdcs_ls*1000))
	((lsadc_sps=rxdcs_ls*1000))
	((hsadc_sps=(txdcs_hs|rxdcs_hs)*1000))
	[ $OBS_DEDICATE_ENABLE = 1 ] && { hsadc_sps=$OBS_DAC_SPS; }

	wait_pps_status=(0 0)
	if [ $((hsadc_sps)) -ne 0 ];then
		echo Starting RFG for HS...;		start_rfg "HS"
		echo Waiting for SYNC on HS...;		wait_for_pps "HS";
		wait_pps_status[1]=$?
	fi
	if [ $((lsdac_sps|lsadc_sps)) -ne 0 ];then
		echo Starting RFG for LS...; 		start_rfg "LS"
		echo Waiting for SYNC on LS...;		wait_for_pps "LS";
		wait_pps_status[0]=$?
	fi
	
	tbgen_init_time=3	#seconds
	l1c_sleep_time=1	#seconds

	rfgstr=""
	echostr="\nTool assumptions of sample rates (must match hardware config)\n"
	echostr="${echostr}===============================================================\n"
	if [ $((hsadc_sps)) -ne 0 ];then
		if [ ${wait_pps_status[1]} -eq 0 ];then
			startoffset_hs=$(get_tbgen_counter "HS")
		else
			rfgstr="${rfgstr}***WARNING: Waiting for SYNC on HS failed, using TBGEN2 master counter current value as base timeline to start HSDCS.\n"
			startoffset_hs=$(get_tbgen_master_counter "HS")
		fi
		startoffset_hs=$((startoffset_hs + tbgen_init_time * tbgen2_freq))
		startoffset_set=HS; startoffset_value=$startoffset_hs
		echostr="${echostr}tbgen2_freq      $tbgen2_freq\n"
		echostr="${echostr}hsdcs_sps        $hsadc_sps\n"
	fi
	if [ $((lsdac_sps|lsadc_sps)) -ne 0 ];then
		if [ ${wait_pps_status[0]} -eq 0 ];then
			startoffset_ls=$(get_tbgen_counter "LS")
		else
			rfgstr="${rfgstr}***WARNING: Waiting for SYNC on LS failed, using TBGEN1 master counter current value as base timeline to start LSDCS.\n"
			startoffset_ls=$(get_tbgen_master_counter "LS")
		fi
		startoffset_ls=$((startoffset_ls + tbgen_init_time * tbgen1_freq))
		startoffset_set=LS; startoffset_value=$startoffset_ls
		echostr="${echostr}tbgen1_freq      $tbgen1_freq\n"
		echostr="${echostr}lsdac_sps        $lsdac_sps\n"
		echostr="${echostr}lsadc_sps        $lsadc_sps\n"
	fi
	echo -e $rfgstr $echostr
	
	l1c=0; l1c_hs=0
	tag=(0 rx tx trx); 	tagintf=(interface interface1 interface2 interface3)

	if ([ $((dcs_enable[4] & BITMASK_ANT_ENABLE_RX)) -ne 0 ] || [ $((dcs_enable[5] & BITMASK_ANT_ENABLE_RX)) -ne 0 ] || [ $OBS_DEDICATE_ENABLE = 1 ]);then
		get_hsadc_outof_low_power_mode
	fi

	TAG_LSHS=(LS LS LS LS HS HS); TAG_LSHS_IDX=(0 1 2 3 0 1); 
	if [ $(((tx_fdd&rx_fdd)|dcsfdd)) -eq 1 ];then     #FDD.  both tx and rx are in FDD mode, set DCS to work in FDD mode
		startoffset=($startoffset_ls $startoffset_hs)
		for((dcsid=0;dcsid<NUM_ANTS;dcsid++))
		do
			trx_enable=${dcs_enable[$dcsid]}
			[ $trx_enable -eq 0 ] && continue
			value=${tag[$trx_enable]}
			echo Enabling ${TAG_LSHS[dcsid]}DCS${TAG_LSHS_IDX[dcsid]} $value in FDD mode at startoffset $(printf 0x%x ${startoffset[dcsid/4]})
			set_tbgen_offset ${TAG_LSHS[dcsid]} ${TAG_LSHS_IDX[dcsid]} $value ${startoffset[dcsid/4]}
		done
		if [ $OBS_DEDICATE_ENABLE = 1 ];then
			echo "Enabling HSDCS0 RX as closed loop observation path"
			enable_dpd_hsadc 0 $startoffset_hs
			echo "Enabling HSDCS1 RX as closed loop observation path"
			enable_dpd_hsadc 1 $startoffset_hs
		fi
			
	else                                     #TDD. both in TDD mode, or TX in TDD while RX in FDD
		if [ $((num_T_LS_enabled+num_R_LS_enabled)) -ne 0 ];then
		for((dcsid=0;dcsid<NUM_ANTS_LS;dcsid++))
		do
			trx_enable=${dcs_enable[$dcsid]}
			if [ $trx_enable -eq 0 ];then
			$e200_cmd_tool -c "l1c config ${tagintf[dcsid]}"
			echo $e200_cmd_tool -c "l1c config ${tagintf[dcsid]}"
			else
			echo Enabling LSDCS$dcsid in TDD mode
			dcsid1=$((dcsid/2)); dcsid2=$((dcsid%2))
			$e200_cmd_tool -c "l1c config ${tagintf[dcsid]} ls$dcsid1 $dcsid2"
			echo $e200_cmd_tool -c "l1c config ${tagintf[dcsid]} ls$dcsid1 $dcsid2"
			l1c=1; one_enabled_dcsid_by_l1c=$dcsid
			fi
			sleep $l1c_sleep_time
		done
		fi
		
		if [ $OBS_DEDICATE_ENABLE = 1 ];then
			echo $e200_cmd_tool -c "l1c config obs_if hs 0 $OBS_PULSE_LEN $((OBS_PULSE_PERIOD*1966080))", OBS_PULSE_PERIOD=$OBS_PULSE_PERIOD
			$e200_cmd_tool -c "l1c config obs_if hs 0 $OBS_PULSE_LEN $((OBS_PULSE_PERIOD*1966080))"
			sleep $l1c_sleep_time
			echo $e200_cmd_tool -c "l1c config obs_if1 hs 1 $OBS_PULSE_LEN $((OBS_PULSE_PERIOD*1966080))", OBS_PULSE_PERIOD=$OBS_PULSE_PERIOD
			$e200_cmd_tool -c "l1c config obs_if1 hs 1 $OBS_PULSE_LEN $((OBS_PULSE_PERIOD*1966080))" 
			sleep $l1c_sleep_time
		fi

		
		([ $scs_ls -ne 30 ] && [ $l1c = 1 ]) && { echo Error: Current version of L1C doesn not support SCS $scs_ls Khz for LSDCS TDD mode, please use FDD mode.; channels_start_fail; }
		
		if [ $l1c = 0 ];then
		for((dcsid=NUM_ANTS_LS;dcsid<NUM_ANTS;dcsid++))
		do
			trx_enable=${dcs_enable[$dcsid]}
			if [ $trx_enable -eq 0 ];then
			$e200_cmd_tool -c "l1c config ${tagintf[dcsid-4]}"
			echo $e200_cmd_tool -c "l1c config ${tagintf[dcsid-4]}"
			else
			echo Enabling HSDCS$((dcsid-4)) in TDD mode
			$e200_cmd_tool -c "l1c config ${tagintf[dcsid-4]} hs $((dcsid-4))"
			echo $e200_cmd_tool -c "l1c config ${tagintf[dcsid-4]} hs $((dcsid-4))"
			l1c_hs=1; one_enabled_dcsid_by_l1c=$dcsid
			fi
			sleep $l1c_sleep_time
		done
		$e200_cmd_tool -c "l1c config ${tagintf[2]}"
		echo $e200_cmd_tool -c "l1c config ${tagintf[2]}"
		sleep $l1c_sleep_time
		$e200_cmd_tool -c "l1c config ${tagintf[3]}"
		echo $e200_cmd_tool -c "l1c config ${tagintf[3]}"
		sleep $l1c_sleep_time
		fi
	
		if [ $l1c_hs = 1 ];then
			$e200_cmd_tool -c "l1c config scs $scs_hs"
			echo $e200_cmd_tool -c "l1c config scs $scs_hs"
			sleep $l1c_sleep_time
		fi
	fi
	
	if [ $((l1c|l1c_hs)) = 1 ];then
		str_pattern="${pattern[@]}"
		$e200_cmd_tool -c "l1c config pattern $str_pattern"
		echo $e200_cmd_tool -c "l1c config pattern $str_pattern"
		sleep $l1c_sleep_time
		
		$e200_cmd_tool -c "l1c config ul_dl_gap $ul_dl_gap"
		echo $e200_cmd_tool -c "l1c config ul_dl_gap $ul_dl_gap"
		sleep $l1c_sleep_time

		$e200_cmd_tool -c "l1c config pps_offset 0"
		echo $e200_cmd_tool -c "l1c config pps_offset 0"
		sleep $l1c_sleep_time
	
		if ([ $rx_fdd = 1 ] || [ $((rx_allowed_ext)) -eq 15 ]);then                              #enable RX FDD in LS or HS
			$e200_cmd_tool -c "l1c config listen yes"
			echo $e200_cmd_tool -c "l1c config listen yes"
			sleep $l1c_sleep_time
		fi

		tag_l1c_start_cpe=(no_vspa_start start_cpe)
		$e200_cmd_tool -c "l1c ${tag_l1c_start_cpe[cpe]}"
		echo $e200_cmd_tool -c "l1c ${tag_l1c_start_cpe[cpe]}"
		echo "L1C start command sent to e200 at VSPA core timestamp $(printf 0x%012x `get_counter vspa $one_dfe_core`)"

		if [ $((l1c)) = 1 ];then  #if LS is TDD, HS will be configured as FDD.
			master_counter_hs=$(get_tbgen_master_counter "HS")
			elapse_l1c=$((master_counter_hs - startoffset_hs))
			elapse_l1c=$((elapse_l1c/tbgen2_freq + 2))                   #add more seconds
			startoffset_hs=$((startoffset_hs + elapse_l1c*tbgen2_freq))  #as L1C TDD config cost too much time, reset start offset
			for((dcsid=NUM_ANTS_LS;dcsid<NUM_ANTS;dcsid++))
			do
				trx_enable=${dcs_enable[$dcsid]}
				[ $trx_enable -eq 0 ] && continue
				if ([ $((trx_enable & BITMASK_ANT_ENABLE_TX)) -ne 0 ] || [ $rx_fdd = 0 ]);then
					str="***WARNING: Current L1C does not support TDD on LS+HS concurrently. Only LS TDD will be enabled. HSDCS$((dcsid-4)) will be configured as FDD.\n"
					echo -e "$str";
					warning_list="$warning_list$str\n"
				fi
				value=${tag[$trx_enable]}
				echo -e "Enabling HSDCS$((dcsid-4)) $value in FDD mode, with ${elapse_l1c}s additional start offset.\n"
				set_tbgen_offset "HS" $((dcsid-4)) $value $startoffset_hs
			done
		fi
		
		one_enabled_dcsid_ctrl_reg=$(get_tdd_ctrl ${TAG_LSHS[$one_enabled_dcsid_by_l1c]} $((one_enabled_dcsid_by_l1c%4)) )
		one_enabled_dcsid_ctrl_reg_v=`./utils/memrw r 32 $one_enabled_dcsid_ctrl_reg`
		wait_count=1000
		while ([ $((one_enabled_dcsid_ctrl_reg_v&1)) -eq 0 ] && [ $wait_count -ne 0 ])
		do
			one_enabled_dcsid_ctrl_reg_v=`./utils/memrw r 32 $one_enabled_dcsid_ctrl_reg`
			wait_count=$((wait_count-1))
			[ $wait_count -eq 0 ] && { echo Timeout waiting e200 L1C TDD logic to enable DCS.; channels_start_fail; }
		done
		l1c_startoffset=$(( (`./utils/memrw r 32 $((one_enabled_dcsid_ctrl_reg+4))`<<32) | `./utils/memrw r 32 $((one_enabled_dcsid_ctrl_reg+8))`))
		echo "l1c will start from TBGEN master counter offset $(printf 0x%x $l1c_startoffset)"
		echo Waiting till tbgen start for l1c...; wait_till_tbgen_tick ${TAG_LSHS[$one_enabled_dcsid_by_l1c]} $((l1c_startoffset+1*tbgen1_freq))

	else
		echo Waiting till tbgen start for FDD mode...; wait_till_tbgen_tick $startoffset_set $startoffset_value

	fi
fi
fi

./check_all.sh

[ $((lphy|use_nxp_l1c)) = 0 ] && echo -e "Waiting for DCS to be enabled. Users have configured to use their own software to enable DCS. \n"
[ "$warning_list" != "" ] && echo -e "$warning_list"
exit 0
